# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 06:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constellation_orderboard', '0002_units'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'permissions': (('action_read_board', 'Can read an order board'), ('action_add_cards', 'Can add cards to an order board'), ('action_move_cards', 'Can move cards on an order board'), ('action_archive_cards', 'Can archive cards from an order board'), ('action_manage_board', 'Can manage an order board'))},
        ),
        migrations.AlterModelOptions(
            name='stage',
            options={},
        ),
        migrations.RemoveField(
            model_name='board',
            name='addGroup',
        ),
        migrations.RemoveField(
            model_name='board',
            name='deleteGroup',
        ),
        migrations.RemoveField(
            model_name='board',
            name='manageGroup',
        ),
        migrations.RemoveField(
            model_name='board',
            name='moveGroup',
        ),
        migrations.RemoveField(
            model_name='board',
            name='readGroup',
        ),
    ]
