language: python
python:
    - "2.7" 
    - "3.4"
    - "3.5"
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-5
            - gcc-5

# command to install dependencies      
install:
    - pip install -r requirements.txt 
    - export CXX="g++-5" CC="gcc-5"

# command to run tests
script:
    - nosetests
