# This file contains map of relationships between objects on source and
# destination clouds.
#
# Use the following format:
# ext_network_map:
#   <old external network id>: <new external network id>
# tenant_map:
#   <old tenant name>: <new tenant name>
#
# F.e.:
#ext_network_map:
#  cfd33270-8a4c-4fb9-8af9-7c83f82b8a5b: 7c325f53-b12b-4b07-b78a-0478d863f625
#
#tenant_map:
#  WTFaaS_BBQoD_Dev_Test: WTFBBQ-313373-V-PZD-05
