# -*- coding: utf-8 -*-
# Copyright (c) 2015, PyRETIS Development Team.
# Distributed under the LGPLv3 License. See LICENSE for more info.
"""Version information for PyRETIS.

This file is generated by PyRETIS (``setup_version.py``)
"""
SHORT_VERSION = '0.9.0.dev1'
VERSION = '0.9.0.dev1'
FULL_VERSION = '0.9.0.dev1'
GIT_REVISION = '1c4d7ccc5b35151b2393f05868f72a5b092bb7c6'
GIT_VERSION = '0.9.0.dev1+1c4d7cc'
RELEASE = False

if not RELEASE:
    VERSION = GIT_VERSION
