language: python
python: 2.7
sudo: false
cache:
  pip: true
  directories:
    - $HOME/buildout-cache
env:
  - PLONE_VERSION=5.0 QA=true
  - PLONE_VERSION=5.1 QA=true
before_install:
  - mkdir -p $HOME/buildout-cache/{eggs,downloads}
  - virtualenv .
  - bin/pip install --upgrade pip setuptools==26.1.1 zc.buildout==2.5.3
install:
  - sed -ie "s#travis-5.x.x.cfg#travis-$PLONE_VERSION.cfg#" travis.cfg
  - bin/buildout -N -t 3 -c travis.cfg
script:
  - bin/code-analysis
  - bin/test
after_success:
  - bin/createcoverage
  - pip install coverage==3.7.1 coveralls
  - coveralls
