application:
  host: "0.0.0.0"
  port: 9000
  usecache: true
logger:
  level: "INFO"
  mode: "console"
  file: "debug.log"
asterisk:
  ami:
    filter:
      use: true
      command: "Event: Bridge"
    timeout: 15
worker:
  docslimit: 10
  enable: false
  timeoutsec: 5
  mongo:
    url: "192.168.1.137:27017"
    connect_timeout_ms: 5000
    server_selection_timeout_ms: 5000
  mysql:
    host: "127.0.0.1"
    port: 3306
    user: "root"
    password: "8888"
    asteriskdb: "asteriskcdrdb"