
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-04-21T11:21:50+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "0417dd37705a45da85e3805564e904dcf28bae68",
 "version": "v1.2.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
