
#ifndef CASADI_INTERPOLANT_LINEAR_EXPORT_H
#define CASADI_INTERPOLANT_LINEAR_EXPORT_H

#ifdef CASADI_INTERPOLANT_LINEAR_STATIC_DEFINE
#  define CASADI_INTERPOLANT_LINEAR_EXPORT
#  define CASADI_INTERPOLANT_LINEAR_NO_EXPORT
#else
#  ifndef CASADI_INTERPOLANT_LINEAR_EXPORT
#    ifdef casadi_interpolant_linear_EXPORTS
        /* We are building this library */
#      define CASADI_INTERPOLANT_LINEAR_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define CASADI_INTERPOLANT_LINEAR_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef CASADI_INTERPOLANT_LINEAR_NO_EXPORT
#    define CASADI_INTERPOLANT_LINEAR_NO_EXPORT 
#  endif
#endif

#ifndef CASADI_INTERPOLANT_LINEAR_DEPRECATED
#  define CASADI_INTERPOLANT_LINEAR_DEPRECATED 
#endif

#ifndef CASADI_INTERPOLANT_LINEAR_DEPRECATED_EXPORT
#  define CASADI_INTERPOLANT_LINEAR_DEPRECATED_EXPORT CASADI_INTERPOLANT_LINEAR_EXPORT CASADI_INTERPOLANT_LINEAR_DEPRECATED
#endif

#ifndef CASADI_INTERPOLANT_LINEAR_DEPRECATED_NO_EXPORT
#  define CASADI_INTERPOLANT_LINEAR_DEPRECATED_NO_EXPORT CASADI_INTERPOLANT_LINEAR_NO_EXPORT CASADI_INTERPOLANT_LINEAR_DEPRECATED
#endif

#define DEFINE_NO_DEPRECATED 0
#if DEFINE_NO_DEPRECATED
# define CASADI_INTERPOLANT_LINEAR_NO_DEPRECATED
#endif

#endif
