
#ifndef CASADI_INTERPOLANT_LINEAR_EXPORT_H
#define CASADI_INTERPOLANT_LINEAR_EXPORT_H

#ifdef CASADI_INTERPOLANT_LINEAR_STATIC_DEFINE
#  define CASADI_INTERPOLANT_LINEAR_EXPORT
#  define CASADI_INTERPOLANT_LINEAR_NO_EXPORT
#else
#  ifndef CASADI_INTERPOLANT_LINEAR_EXPORT
#    ifdef casadi_interpolant_linear_EXPORTS
        /* We are building this library */
#      define CASADI_INTERPOLANT_LINEAR_EXPORT __attribute__((visibility("default")))
#    else
        /* We are using this library */
#      define CASADI_INTERPOLANT_LINEAR_EXPORT __attribute__((visibility("default")))
#    endif
#  endif

#  ifndef CASADI_INTERPOLANT_LINEAR_NO_EXPORT
#    define CASADI_INTERPOLANT_LINEAR_NO_EXPORT __attribute__((visibility("hidden")))
#  endif
#endif

#ifndef CASADI_INTERPOLANT_LINEAR_DEPRECATED
#  define CASADI_INTERPOLANT_LINEAR_DEPRECATED __attribute__ ((__deprecated__))
#endif

#ifndef CASADI_INTERPOLANT_LINEAR_DEPRECATED_EXPORT
#  define CASADI_INTERPOLANT_LINEAR_DEPRECATED_EXPORT CASADI_INTERPOLANT_LINEAR_EXPORT CASADI_INTERPOLANT_LINEAR_DEPRECATED
#endif

#ifndef CASADI_INTERPOLANT_LINEAR_DEPRECATED_NO_EXPORT
#  define CASADI_INTERPOLANT_LINEAR_DEPRECATED_NO_EXPORT CASADI_INTERPOLANT_LINEAR_NO_EXPORT CASADI_INTERPOLANT_LINEAR_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef CASADI_INTERPOLANT_LINEAR_NO_DEPRECATED
#    define CASADI_INTERPOLANT_LINEAR_NO_DEPRECATED
#  endif
#endif

#endif
