
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-04-26T16:21:46+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "55b42c5afd20016b966994cbff3ee7cd0c38d2db",
 "version": "0.7.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
