# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omCmsMain', '0004_auto_20170320_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryitem',
            name='itemMouseOver',
        ),
        migrations.AddField(
            model_name='categoryitem',
            name='itemStyle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sitemaininfo',
            name='displayImageHeader',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitemaininfo',
            name='displayLogo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitemaininfo',
            name='displayNavBar',
            field=models.BooleanField(default=True),
        ),
    ]
