# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omCmsMain', '0013_sitemaininfo_sitehomelabel'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitemaininfo',
            name='siteTheme',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
