# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omCmsMain', '0025_auto_20170328_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentarticle',
            name='body1Image',
            field=models.ImageField(blank=True, null=True, upload_to='siteImages/'),
        ),
        migrations.AlterField(
            model_name='contentarticle',
            name='body2Image',
            field=models.ImageField(blank=True, null=True, upload_to='siteImages/'),
        ),
        migrations.AlterField(
            model_name='contentarticle',
            name='body3Image',
            field=models.ImageField(blank=True, null=True, upload_to='siteImages/'),
        ),
        migrations.AlterField(
            model_name='contentarticle',
            name='teaserImage',
            field=models.ImageField(blank=True, null=True, upload_to='siteImages/'),
        ),
    ]
