# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omCmsMain', '0034_auto_20170411_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentarticle',
            name='slug',
            field=models.SlugField(default=' '),
            preserve_default=False,
        ),
    ]
