# coding: utf-8

"""
    Schul-Cloud Content API

    This is the specification for the content of Schul-Cloud. You can find more information in the repository <https://github.com/schul-cloud/ressources-api-v1>. 

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import schul_cloud_ressources_api_v1
from schul_cloud_ressources_api_v1.rest import ApiException
from schul_cloud_ressources_api_v1.models.content_category import ContentCategory


class TestContentCategory(unittest.TestCase):
    """ ContentCategory unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testContentCategory(self):
        """
        Test ContentCategory
        """
        model = schul_cloud_ressources_api_v1.models.content_category.ContentCategory()


if __name__ == '__main__':
    unittest.main()
