# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visaweb', '0003_auto_20170311_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisaDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('connected', models.BooleanField(default=False)),
                ('alias', models.CharField(default='d75170e7-8b3e-4587-8e94-e7600d05d068', max_length=200)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='visaevent',
            name='request',
            field=models.CharField(default='?IDN', max_length=200),
        ),
        migrations.AlterField(
            model_name='visaevent',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visaweb.VisaDevice'),
        ),
        migrations.AlterField(
            model_name='visaevent',
            name='success',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='VisaSession',
        ),
    ]
