# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visaweb', '0004_auto_20170311_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visadevice',
            name='alias',
            field=models.CharField(default='afa489db-72a8-43ae-a428-2b53dc46bf72', max_length=200),
        ),
    ]
