# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visaweb', '0006_auto_20170311_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visadevice',
            name='alias',
            field=models.CharField(default='ce2fd230-7b39-460f-8c4b-f133abb90884', max_length=200),
        ),
    ]
