# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visaweb', '0009_auto_20170311_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visadevice',
            name='alias',
            field=models.CharField(default='389d63d0-6ce6-495d-a744-9b859c628727', max_length=200),
        ),
    ]
