# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visaweb', '0013_auto_20170311_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visadevice',
            name='alias',
            field=models.CharField(default='16b62231-69cc-409c-81b6-bd718a230c8f', max_length=200),
        ),
    ]
