# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 14:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assetadapter', '0001_initial'),
        ('processengine', '0002_auto_20170423_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataentry',
            name='unit',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='assetadapter.EnumerationChoice'),
        ),
    ]
