---
- name: Upgrade all packages
  yum:
    name: '*'
    state: latest

- name: Get instance metadata from AWS API
  uri:
    url: http://169.254.169.254/latest/meta-data/instance-id
    return_content: yes
  register: local_instance_id

- name: Set hostname
  hostname:
    name: "{{item.1.tags.Name}}{{item.0 + 1}}.{{domain}}"
  with_indexed_items: "{{hostvars.localhost.created_instances.tagged_instances}}"
  when: item.1.id == local_instance_id.content
