heat_template_version: ocata

description: >
  OpenStack containerized Aodh Listener service

parameters:
  DockerNamespace:
    description: namespace
    default: 'tripleoupstream'
    type: string
  DockerAodhListenerImage:
    description: image
    default: 'centos-binary-aodh-listener:latest'
    type: string
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json

resources:

  AodhListenerBase:
    type: ../../puppet/services/aodh-listener.yaml
    properties:
      EndpointMap: {get_param: EndpointMap}
      ServiceNetMap: {get_param: ServiceNetMap}
      DefaultPasswords: {get_param: DefaultPasswords}

outputs:
  role_data:
    description: Role data for the Aodh API role.
    value:
      service_name: {get_attr: [AodhListenerBase, role_data, service_name]}
      config_settings:
        map_merge:
          - get_attr: [AodhListenerBase, role_data, config_settings]
      step_config: &step_config
        get_attr: [AodhListenerBase, role_data, step_config]
      service_config_settings: {get_attr: [AodhListenerBase, role_data, service_config_settings]}
      # BEGIN DOCKER SETTINGS
      puppet_config:
        config_volume: aodh
        puppet_tags: aodh_config
        step_config: *step_config
        config_image: &aodh_listener_image
          list_join:
            - '/'
            - [ {get_param: DockerNamespace}, {get_param: DockerAodhListenerImage} ]
      kolla_config:
        /var/lib/kolla/config_files/aodh-listener.json:
          command: /usr/bin/aodh-listener
      docker_config:
        step_4:
          aodh_listener:
            image: *aodh_listener_image
            net: host
            privileged: false
            restart: always
            volumes:
              - /var/lib/kolla/config_files/aodh-listener.json:/var/lib/kolla/config_files/config.json:ro
              - /var/lib/config-data/aodh/etc/aodh/:/etc/aodh/:ro
              - /etc/hosts:/etc/hosts:ro
              - /etc/localtime:/etc/localtime:ro
            environment:
              - KOLLA_CONFIG_STRATEGY=COPY_ALWAYS
      upgrade_tasks:
        - name: Stop and disable openstack-aodh-listener service
          tags: step2
          service: name=openstack-aodh-listener.service state=stopped enabled=no
