heat_template_version: ocata

description: >
  OpenStack Glance service configured with Puppet

parameters:
  DockerNamespace:
    description: namespace
    default: 'tripleoupstream'
    type: string
  DockerGlanceApiImage:
    description: image
    default: 'centos-binary-glance-api:latest'
    type: string
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json

resources:

  GlanceApiPuppetBase:
    type: ../../puppet/services/glance-api.yaml
    properties:
      EndpointMap: {get_param: EndpointMap}
      ServiceNetMap: {get_param: ServiceNetMap}
      DefaultPasswords: {get_param: DefaultPasswords}

outputs:
  role_data:
    description: Role data for the Glance API role.
    value:
      service_name: {get_attr: [GlanceApiPuppetBase, role_data, service_name]}
      config_settings:
        map_merge:
          - get_attr: [GlanceApiPuppetBase, role_data, config_settings]
          - glance::api::sync_db: false
      step_config: &step_config
        get_attr: [GlanceApiPuppetBase, role_data, step_config]
      service_config_settings: {get_attr: [GlanceApiPuppetBase, role_data, service_config_settings]}
      # BEGIN DOCKER SETTINGS #
      puppet_config:
        config_volume: glance_api
        puppet_tags: glance_api_config,glance_api_paste_ini,glance_swift_config,glance_cache_config
        step_config: *step_config
        config_image: &glance_image
          list_join:
            - '/'
            - [ {get_param: DockerNamespace}, {get_param: DockerGlanceApiImage} ]
      kolla_config:
        /var/lib/kolla/config_files/glance-api.json:
          command: /usr/bin/glance-api --config-file /usr/share/glance/glance-api-dist.conf --config-file /etc/glance/glance-api.conf
      docker_config:
        step_3:
          glance_api_db_sync:
            image: *glance_image
            net: host
            privileged: false
            detach: false
            volumes: &glance_volumes
              - /var/lib/kolla/config_files/glance-api.json:/var/lib/kolla/config_files/config.json
              - /var/lib/config-data/glance_api/etc/glance/:/etc/glance/:ro
              - /etc/localtime:/etc/localtime:ro
              - /lib/modules:/lib/modules:ro
              - /run:/run
              - /dev:/dev
              - /etc/hosts:/etc/hosts:ro
            environment:
              - KOLLA_BOOTSTRAP=True
              - KOLLA_CONFIG_STRATEGY=COPY_ALWAYS
        step_4:
          glance_api:
            image: *glance_image
            net: host
            privileged: false
            restart: always
            volumes: *glance_volumes
            environment:
              - KOLLA_CONFIG_STRATEGY=COPY_ALWAYS
      upgrade_tasks:
        - name: Stop and disable glance_api service
          tags: step2
          service: name=openstack-glance-api state=stopped enabled=no
