heat_template_version: ocata

description: >
  OpenStack containerized Gnocchi Statsd service

parameters:
  DockerNamespace:
    description: namespace
    default: 'tripleoupstream'
    type: string
  DockerGnocchiStatsdImage:
    description: image
    default: 'centos-binary-gnocchi-statsd:latest'
    type: string
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json

resources:

  GnocchiStatsdBase:
    type: ../../puppet/services/gnocchi-statsd.yaml
    properties:
      EndpointMap: {get_param: EndpointMap}
      ServiceNetMap: {get_param: ServiceNetMap}
      DefaultPasswords: {get_param: DefaultPasswords}

outputs:
  role_data:
    description: Role data for the Gnocchi API role.
    value:
      service_name: {get_attr: [GnocchiStatsdBase, role_data, service_name]}
      config_settings: {get_attr: [GnocchiStatsdBase, role_data, config_settings]}
      step_config: &step_config
        get_attr: [GnocchiStatsdBase, role_data, step_config]
      service_config_settings: {get_attr: [GnocchiStatsdBase, role_data, service_config_settings]}
      # BEGIN DOCKER SETTINGS
      puppet_config:
        config_volume: gnocchi
        puppet_tags: gnocchi_config
        step_config: *step_config
        config_image: &gnocchi_statsd_image
          list_join:
            - '/'
            - [ {get_param: DockerNamespace}, {get_param: DockerGnocchiStatsdImage} ]
      kolla_config:
        /var/lib/kolla/config_files/gnocchi-statsd.json:
          command: /usr/bin/gnocchi-statsd
      docker_config:
        step_4:
          gnocchi_statsd:
            image: *gnocchi_statsd_image
            net: host
            privileged: false
            restart: always
            volumes:
              - /var/lib/kolla/config_files/gnocchi-statsd.json:/var/lib/kolla/config_files/config.json:ro
              - /var/lib/config-data/gnocchi/etc/gnocchi/:/etc/gnocchi/:ro
              - /etc/hosts:/etc/hosts:ro
              - /etc/localtime:/etc/localtime:ro
            environment:
              - KOLLA_CONFIG_STRATEGY=COPY_ALWAYS
