heat_template_version: ocata

description: >
  OpenStack containerized Ironic API service

parameters:
  DockerNamespace:
    description: namespace
    default: 'tripleoupstream'
    type: string
  DockerIronicApiImage:
    description: image
    default: 'centos-binary-ironic-api:latest'
    type: string
  DockerIronicConfigImage:
    description: image
    default: 'centos-binary-ironic-pxe:latest'
    type: string
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json

resources:

  IronicApiBase:
    type: ../../puppet/services/ironic-api.yaml
    properties:
      EndpointMap: {get_param: EndpointMap}
      ServiceNetMap: {get_param: ServiceNetMap}
      DefaultPasswords: {get_param: DefaultPasswords}

outputs:
  role_data:
    description: Role data for the Ironic API role.
    value:
      service_name: {get_attr: [IronicApiBase, role_data, service_name]}
      config_settings:
        map_merge:
          - get_attr: [IronicApiBase, role_data, config_settings]
      step_config: &step_config
        get_attr: [IronicApiBase, role_data, step_config]
      service_config_settings: {get_attr: [IronicApiBase, role_data, service_config_settings]}
      # BEGIN DOCKER SETTINGS
      puppet_config:
        config_volume: ironic
        puppet_tags: ironic_config
        step_config: *step_config
        config_image:
          list_join:
            - '/'
            - [ {get_param: DockerNamespace}, {get_param: DockerIronicConfigImage} ]
      kolla_config:
        /var/lib/kolla/config_files/ironic_api.json:
          command: /usr/bin/ironic-api
      docker_config:
        step_3:
          ironic_db_sync:
            image: &ironic_image
              list_join:
                - '/'
                - [ {get_param: DockerNamespace}, {get_param: DockerIronicApiImage} ]
            net: host
            privileged: false
            detach: false
            volumes:
              - /var/lib/config-data/ironic/etc/:/etc/:ro
              - /etc/hosts:/etc/hosts:ro
              - /etc/localtime:/etc/localtime:ro
            command: ['ironic-dbsync', '--config-file', '/etc/ironic/ironic.conf']
        step_4:
          ironic_api:
            start_order: 10
            image: *ironic_image
            net: host
            privileged: false
            restart: always
            volumes:
              - /var/lib/kolla/config_files/ironic_api.json:/var/lib/kolla/config_files/config.json:ro
              - /var/lib/config-data/ironic/etc/:/etc/:ro
              - /etc/hosts:/etc/hosts:ro
              - /etc/localtime:/etc/localtime:ro
            environment:
              - KOLLA_CONFIG_STRATEGY=COPY_ALWAYS
      upgrade_tasks:
        - name: Stop and disable ironic_api service
          tags: step2
          service: name=openstack-ironic-api state=stopped enabled=no
