heat_template_version: ocata

description: >
  OpenStack containerized Neutron L3 agent

parameters:
  DockerNamespace:
    description: namespace
    default: 'tripleoupstream'
    type: string
  DockerNeutronL3AgentImage:
    description: image
    default: 'centos-binary-neutron-l3-agent:latest'
    type: string
  # we configure all neutron services in the same neutron
  DockerNeutronConfigImage:
    description: image
    default: 'centos-binary-neutron-openvswitch-agent:latest'
    type: string
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json

resources:

  NeutronL3Base:
    type: ../../puppet/services/neutron-l3.yaml
    properties:
      EndpointMap: {get_param: EndpointMap}
      ServiceNetMap: {get_param: ServiceNetMap}
      DefaultPasswords: {get_param: DefaultPasswords}

outputs:
  role_data:
    description: Role data for Neutron L3 agent
    value:
      service_name: {get_attr: [NeutronL3Base, role_data, service_name]}
      config_settings: {get_attr: [NeutronL3Base, role_data, config_settings]}
      step_config: &step_config
        get_attr: [NeutronL3Base, role_data, step_config]
      puppet_config:
        puppet_tags: neutron_config,neutron_l3_agent_config
        config_volume: neutron
        step_config: *step_config
        config_image:
          list_join:
            - '/'
            - [ {get_param: DockerNamespace}, {get_param: DockerNeutronConfigImage} ]
      kolla_config:
        /var/lib/kolla/config_files/neutron-l3-agent.json:
          command: /usr/bin/neutron-l3-agent --config-file /usr/share/neutron/neutron-dist.conf --config-dir /usr/share/neutron/l3_agent --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/l3_agent.ini
      docker_config:
        step_4:
          neutronl3agent:
            image:
              list_join:
                - '/'
                - [ {get_param: DockerNamespace}, {get_param: DockerNeutronL3AgentImage} ]
            net: host
            pid: host
            privileged: true
            restart: always
            volumes:
              - /var/lib/kolla/config_files/neutron-l3-agent.json:/var/lib/kolla/config_files/config.json:ro
              - /var/lib/config-data/neutron/etc/neutron/:/etc/neutron/:ro
              - /etc/localtime:/etc/localtime:ro
              - /lib/modules:/lib/modules:ro
              - /run:/run
            environment:
              - KOLLA_CONFIG_STRATEGY=COPY_ALWAYS
