heat_template_version: ocata

description: >
  OpenStack containerized Nova Scheduler service

parameters:
  DockerNamespace:
    description: namespace
    default: 'tripleoupstream'
    type: string
  DockerNovaSchedulerImage:
    description: image
    default: 'centos-binary-nova-scheduler:latest'
    type: string
  DockerNovaConfigImage:
    description: image
    default: 'centos-binary-nova-base:latest'
    type: string
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json

resources:

  NovaSchedulerBase:
    type: ../../puppet/services/nova-scheduler.yaml
    properties:
      EndpointMap: {get_param: EndpointMap}
      ServiceNetMap: {get_param: ServiceNetMap}
      DefaultPasswords: {get_param: DefaultPasswords}

outputs:
  role_data:
    description: Role data for the Nova Scheduler service.
    value:
      service_name: {get_attr: [NovaSchedulerBase, role_data, service_name]}
      config_settings: {get_attr: [NovaSchedulerBase, role_data, config_settings]}
      step_config: &step_config
        get_attr: [NovaSchedulerBase, role_data, step_config]
      service_config_settings: {get_attr: [NovaSchedulerBase, role_data, service_config_settings]}
      # BEGIN DOCKER SETTINGS
      puppet_config:
        config_volume: nova
        puppet_tags: nova_config
        step_config: *step_config
        config_image:
          list_join:
          - '/'
          - [ {get_param: DockerNamespace}, {get_param: DockerNovaConfigImage} ]
      kolla_config:
        /var/lib/kolla/config_files/nova_scheduler.json:
          command: /usr/bin/nova-scheduler
      docker_config:
        step_4:
          nova_scheduler:
            image:
              list_join:
                - '/'
                - [ {get_param: DockerNamespace}, {get_param: DockerNovaSchedulerImage} ]
            net: host
            privileged: false
            restart: always
            volumes:
              - /var/lib/kolla/config_files/nova_scheduler.json:/var/lib/kolla/config_files/config.json:ro
              - /var/lib/config-data/nova/etc/nova/:/etc/nova/:ro
              - /etc/hosts:/etc/hosts:ro
              - /etc/localtime:/etc/localtime:ro
              - /run:/run
            environment:
              - KOLLA_CONFIG_STRATEGY=COPY_ALWAYS
      upgrade_tasks:
        - name: Stop and disable nova_scheduler service
          tags: step2
          service: name=openstack-nova-scheduler state=stopped enabled=no
