heat_template_version: ocata

description: >
  OpenStack Libvirt Service

parameters:
  DockerNamespace:
    description: namespace
    default: 'tripleoupstream'
    type: string
  DockerLibvirtImage:
    description: image
    default: 'centos-binary-nova-libvirt:latest'
    type: string
  # we configure libvirt via the nova-compute container due to coupling
  # in the puppet modules
  DockerNovaConfigImage:
    description: image
    default: 'centos-binary-nova-compute:latest'
    type: string
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json

resources:

  NovaLibvirtBase:
    type: ../../puppet/services/nova-libvirt.yaml
    properties:
      EndpointMap: {get_param: EndpointMap}
      ServiceNetMap: {get_param: ServiceNetMap}
      DefaultPasswords: {get_param: DefaultPasswords}

outputs:
  role_data:
    description: Role data for the Libvirt service.
    value:
      service_name: {get_attr: [NovaLibvirtBase, role_data, service_name]}
      config_settings: {get_attr: [NovaLibvirtBase, role_data, config_settings]}
      step_config: &step_config
        get_attr: [NovaLibvirtBase, role_data, step_config]
      puppet_config:
        config_volume: nova_libvirt
        puppet_tags: nova_config
        step_config: *step_config
        config_image:
          list_join:
          - '/'
          - [ {get_param: DockerNamespace}, {get_param: DockerNovaConfigImage} ]
      kolla_config:
        /var/lib/kolla/config_files/nova-libvirt.json:
          command: /usr/sbin/libvirtd --config /etc/libvirt/libvirtd.conf
      docker_config:
        step_3:
          nova_libvirt:
            image:
              list_join:
              - '/'
              - [ {get_param: DockerNamespace}, {get_param: DockerLibvirtImage} ]
            net: host
            pid: host
            privileged: true
            restart: always
            volumes:
              - /var/lib/kolla/config_files/nova-libvirt.json:/var/lib/kolla/config_files/config.json:ro
              - /var/lib/config-data/nova_libvirt/etc/libvirt/:/etc/libvirt/:ro
              - /etc/localtime:/etc/localtime:ro
              - /lib/modules:/lib/modules:ro
              - /dev:/dev
              - /run:/run
              - /sys/fs/cgroup:/sys/fs/cgroup
              - /var/lib/nova:/var/lib/nova
              # Needed to use host's virtlogd
              - /var/run/libvirt:/var/run/libvirt
              - /var/lib/libvirt:/var/lib/libvirt
              - /etc/libvirt/qemu:/etc/libvirt/qemu
            environment:
              - KOLLA_CONFIG_STRATEGY=COPY_ALWAYS
      host_prep_tasks:
        - name: create libvirt persistent data directories
          file:
            path: "{{ item }}"
            state: directory
          with_items:
            - /etc/libvirt/qemu
            - /var/lib/libvirt
      upgrade_tasks:
        - name: Stop and disable libvirtd service
          tags: step2
          service: name=libvirtd state=stopped enabled=no
