heat_template_version: ocata

description: >
  OpenStack containerized Nova Placement API service

parameters:
  DockerNamespace:
    description: namespace
    default: 'tripleoupstream'
    type: string
  DockerNovaPlacementImage:
    description: image
    default: 'centos-binary-nova-placement-api'
    type: string
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json

resources:

  NovaPlacementBase:
    type: ../../puppet/services/nova-placement.yaml
    properties:
      EndpointMap: {get_param: EndpointMap}
      ServiceNetMap: {get_param: ServiceNetMap}
      DefaultPasswords: {get_param: DefaultPasswords}

outputs:
  role_data:
    description: Role data for the Nova Placement API role.
    value:
      service_name: {get_attr: [NovaPlacementBase, role_data, service_name]}
      config_settings:
        map_merge:
          - get_attr: [NovaPlacementBase, role_data, config_settings]
          - apache::default_vhost: false
      step_config: &step_config
        get_attr: [NovaPlacementBase, role_data, step_config]
      service_config_settings: {get_attr: [NovaPlacementBase, role_data, service_config_settings]}
      # BEGIN DOCKER SETTINGS
      puppet_config:
        config_volume: nova_placement
        puppet_tags: nova_config
        step_config: *step_config
        config_image: &nova_placement_image
          list_join:
          - '/'
          - [ {get_param: DockerNamespace}, {get_param: DockerNovaPlacementImage} ]
      kolla_config:
        /var/lib/kolla/config_files/nova_placement.json:
          command: /usr/sbin/httpd -DFOREGROUND
      docker_config:
        # start this early so it is up before computes start reporting
        step_3:
          nova_placement:
            start_order: 1
            image: *nova_placement_image
            net: host
            user: root
            restart: always
            volumes:
              - /var/lib/kolla/config_files/nova_placement.json:/var/lib/kolla/config_files/config.json:ro
              - /var/lib/config-data/nova_placement/etc/nova/:/etc/nova/:ro
              - /var/lib/config-data/nova_placement/etc/httpd/:/etc/httpd/:ro
              - /var/lib/config-data/nova_placement/var/www/:/var/www/:ro
              - /etc/hosts:/etc/hosts:ro
              - /etc/localtime:/etc/localtime:ro
            environment:
              - KOLLA_CONFIG_STRATEGY=COPY_ALWAYS
      upgrade_tasks:
        - name: Stop and disable nova_placement service (running under httpd)
          tags: step2
          service: name=httpd state=stopped enabled=no
