heat_template_version: ocata

description: >
  OpenStack containerized Nova Ironic Compute service

parameters:
  DockerNamespace:
    description: namespace
    default: 'tripleoupstream'
    type: string
  DockerNovaComputeImage:
    description: image
    default: 'centos-binary-nova-compute-ironic:latest'
    type: string
  DockerNovaConfigImage:
    description: image
    default: 'centos-binary-nova-base:latest'
    type: string
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json

resources:


  NovaIronicBase:
    type: ../../puppet/services/nova-ironic.yaml
    properties:
      EndpointMap: {get_param: EndpointMap}

outputs:
  role_data:
    description: Role data for the Nova Compute service.
    value:
      service_name: {get_attr: [NovaIronicBase, role_data, service_name]}
      config_settings: {get_attr: [NovaIronicBase, role_data, config_settings]}
      step_config: &step_config
        get_attr: [NovaIronicBase, role_data, step_config]
      puppet_config:
        config_volume: nova
        puppet_tags: nova_config,nova_paste_api_ini
        step_config: *step_config
        config_image:
          list_join:
          - '/'
          - [ {get_param: DockerNamespace}, {get_param: DockerNovaConfigImage} ]
      kolla_config:
        /var/lib/kolla/config_files/nova_ironic.json:
           command: /usr/bin/nova-compute --config-file /etc/nova/nova.conf --config-file /etc/nova/rootwrap.conf
      docker_config:
        step_5:
          novacompute:
            image:
              list_join:
              - '/'
              - [ {get_param: DockerNamespace}, {get_param: DockerNovaComputeImage} ]
            net: host
            privileged: true
            user: root
            restart: always
            volumes:
              - /var/lib/kolla/config_files/nova_ironic.json:/var/lib/kolla/config_files/config.json:ro
              - /var/lib/config-data/nova/etc/nova/:/etc/nova/:ro
              - /etc/localtime:/etc/localtime:ro
              - /run:/run
              - /dev:/dev
              - /etc/iscsi:/etc/iscsi
              - /var/lib/nova/:/var/lib/nova
            environment:
             - KOLLA_CONFIG_STRATEGY=COPY_ALWAYS
      upgrade_tasks:
        - name: Stop and disable nova-compute service
          tags: step2
          service: name=nova-compute state=stopped enabled=no
