= feedcommas(1)
:doctype: manpage
:author: Michał Góral
:email: dev@mgoral.org
:revnumber: @VERSION@
:man manual: Feed Commas Manual
:man source: Feed Commas {revnumber}
:manual-url: http://pythonhosted.org/feedcommas/

== NAME

feed-commas - user-friendly console CommaFeed client.

== SYNOPSIS

*feed-commas* [_OPTIONS_] ..

== OPTIONS

include::manual/program-options.adoc[tags=manpage]

== CONFIGURATION

include::manual/config.adoc[tags=manpage]

== COPYRIGHT

Copyright (C) 2017 {author}.

Feed Commas is free software: you can redistribute it and/or modify it under the
terms of the GNU General Public License as published by the Free Software
Foundation, either version 3 of the License, or (at your option) any later
version.

Feed Commas is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.

== BUGS AND ISSUES

Please report any bugs at https://gitlab.com/mgoral/feed-commas/issues.

== SEE ALSO

=== Full Documentation

This man page doesn't cover the whole usage of Feed Commas. A complete manual is
available online: {manual-url}.

You can also generate it by running *make* inside Feed Commas' *docs* directory.
