
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "0022de62c1d846658f42e9b7a2497560168c1e13",
 "version": "0.0.0a41"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
