---
# Create k8sdc-ca certificate authority
- name: Install openssl
  yum:
    name:  openssl
    state: installed

- name: Create CA directory
  file:
    path:  /etc/k8sdc-ca/
    state: directory
    mode:  0750

- name: Stat k8sdc-ca.key
  stat:
    path: /etc/k8sdc-ca/k8sdc-ca.key
  register: k8sdc_ca_key_file

- block:

  - name: Generate CA private key
    command: openssl genrsa -out k8sdc-ca.key 2048
    args:
      chdir: /etc/k8sdc-ca/

  - name: Generate CA self signed certificate
    command: >
        openssl req -x509 -new -nodes 
                    -key k8sdc-ca.key 
                    -days 10000 
                    -out k8sdc-ca.crt 
                    -subj "/CN=k8sdc-ca"
    args:
      chdir: /etc/k8sdc-ca/

  when: not k8sdc_ca_key_file.stat.exists or k8s_regen_certs
