
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "9c79e98bfd77caac3d1b77881cf2a9d56c1e65d3",
 "version": "2.2.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
