
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "442286073fb03a71a9bf01b7f2f67dc11d8595a3",
 "version": "0.post.dev425"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
