heat_template_version: ocata

description: >
  Configures docker on the host

parameters:
  DockerNamespace:
    description: namespace
    default: tripleoupstream
    type: string
  DockerNamespaceIsRegistry:
    type: boolean
    default: false
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json

outputs:
  role_data:
    description: Role data for the docker service
    value:
      service_name: docker
      config_settings:
        tripleo::profile::base::docker::docker_namespace: {get_param: DockerNamespace}
        tripleo::profile::base::docker::insecure_registry: {get_param: DockerNamespaceIsRegistry}
      step_config: |
        include ::tripleo::profile::base::docker
      upgrade_tasks:
        - name: Install docker packages on upgrade if missing
          tags: step3
          yum: name=docker state=latest

