heat_template_version: ocata

description: >
  Configure securetty values

parameters:
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  TtyValues:
    default: {}
    description: Configures console values in securetty
    type: json
    constraints:
      - length: { min: 1}

outputs:
  role_data:
    description: Console data for the securetty
    value:
      service_name: securetty
      config_settings:
        tripleo::profile::base::securetty::tty_list: {get_param: TtyValues}
      step_config: |
        include ::tripleo::profile::base::securetty
