
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "692b08fc9b11d4e0f058064c5b76770d83401f14",
 "version": "1.9.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
