# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visaweb', '0007_auto_20170311_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visadevice',
            name='alias',
            field=models.CharField(default='2d1e9c62-3aea-4dea-8840-6d13236b1b81', max_length=200),
        ),
    ]
