# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visaweb', '0011_auto_20170311_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visadevice',
            name='alias',
            field=models.CharField(default='b46e1138-5937-42e1-95ec-e7e45c7566ad', max_length=200),
        ),
    ]
