# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BladePy0_1_1\software_core\output_viewerUI.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1196, 866)
        MainWindow.setToolTip(_fromUtf8(""))
        MainWindow.setStatusTip(_fromUtf8(""))
        MainWindow.setWhatsThis(_fromUtf8(""))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.centralwidget_hl = QtGui.QHBoxLayout(self.centralwidget)
        self.centralwidget_hl.setObjectName(_fromUtf8("centralwidget_hl"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.ui_file_toolbar = QtGui.QToolBar(MainWindow)
        self.ui_file_toolbar.setObjectName(_fromUtf8("ui_file_toolbar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.ui_file_toolbar)
        self.ui_view_toolbar = QtGui.QToolBar(MainWindow)
        self.ui_view_toolbar.setObjectName(_fromUtf8("ui_view_toolbar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.ui_view_toolbar)
        self.ui_treeview_dockW = QtGui.QDockWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_treeview_dockW.sizePolicy().hasHeightForWidth())
        self.ui_treeview_dockW.setSizePolicy(sizePolicy)
        self.ui_treeview_dockW.setMinimumSize(QtCore.QSize(190, 300))
        self.ui_treeview_dockW.setMaximumSize(QtCore.QSize(500, 524287))
        self.ui_treeview_dockW.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.ui_treeview_dockW.setObjectName(_fromUtf8("ui_treeview_dockW"))
        self.ui_treeview_dockcontents = QtGui.QWidget()
        self.ui_treeview_dockcontents.setObjectName(_fromUtf8("ui_treeview_dockcontents"))
        self.ui_treeview_dockcontents_vl = QtGui.QVBoxLayout(self.ui_treeview_dockcontents)
        self.ui_treeview_dockcontents_vl.setObjectName(_fromUtf8("ui_treeview_dockcontents_vl"))
        self.ui_case_treeview = QtGui.QTreeView(self.ui_treeview_dockcontents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_case_treeview.sizePolicy().hasHeightForWidth())
        self.ui_case_treeview.setSizePolicy(sizePolicy)
        self.ui_case_treeview.setMinimumSize(QtCore.QSize(0, 80))
        self.ui_case_treeview.setSortingEnabled(False)
        self.ui_case_treeview.setAnimated(True)
        self.ui_case_treeview.setHeaderHidden(False)
        self.ui_case_treeview.setObjectName(_fromUtf8("ui_case_treeview"))
        self.ui_treeview_dockcontents_vl.addWidget(self.ui_case_treeview)
        self.ui_subcase_list = QtGui.QListWidget(self.ui_treeview_dockcontents)
        self.ui_subcase_list.setMinimumSize(QtCore.QSize(0, 10))
        self.ui_subcase_list.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.ui_subcase_list.setObjectName(_fromUtf8("ui_subcase_list"))
        self.ui_treeview_dockcontents_vl.addWidget(self.ui_subcase_list)
        self.ui_deletecase_btn = QtGui.QPushButton(self.ui_treeview_dockcontents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_deletecase_btn.sizePolicy().hasHeightForWidth())
        self.ui_deletecase_btn.setSizePolicy(sizePolicy)
        self.ui_deletecase_btn.setObjectName(_fromUtf8("ui_deletecase_btn"))
        self.ui_treeview_dockcontents_vl.addWidget(self.ui_deletecase_btn)
        self.ui_treeview_dockW.setWidget(self.ui_treeview_dockcontents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.ui_treeview_dockW)
        self.ui_propertiestools_dockW = QtGui.QDockWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_propertiestools_dockW.sizePolicy().hasHeightForWidth())
        self.ui_propertiestools_dockW.setSizePolicy(sizePolicy)
        self.ui_propertiestools_dockW.setMinimumSize(QtCore.QSize(382, 496))
        self.ui_propertiestools_dockW.setMaximumSize(QtCore.QSize(500, 524287))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.ui_propertiestools_dockW.setFont(font)
        self.ui_propertiestools_dockW.setObjectName(_fromUtf8("ui_propertiestools_dockW"))
        self.ui_propertiestools_dockcontents = QtGui.QWidget()
        self.ui_propertiestools_dockcontents.setObjectName(_fromUtf8("ui_propertiestools_dockcontents"))
        self.ui_propertiestools_dockcontents_gl = QtGui.QGridLayout(self.ui_propertiestools_dockcontents)
        self.ui_propertiestools_dockcontents_gl.setObjectName(_fromUtf8("ui_propertiestools_dockcontents_gl"))
        self.ui_selectedcase_edit = QtGui.QLineEdit(self.ui_propertiestools_dockcontents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_selectedcase_edit.sizePolicy().hasHeightForWidth())
        self.ui_selectedcase_edit.setSizePolicy(sizePolicy)
        self.ui_selectedcase_edit.setMaximumSize(QtCore.QSize(16777215, 23))
        self.ui_selectedcase_edit.setObjectName(_fromUtf8("ui_selectedcase_edit"))
        self.ui_propertiestools_dockcontents_gl.addWidget(self.ui_selectedcase_edit, 1, 0, 1, 2)
        self.ui_zoom_lbl = QtGui.QLabel(self.ui_propertiestools_dockcontents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_zoom_lbl.sizePolicy().hasHeightForWidth())
        self.ui_zoom_lbl.setSizePolicy(sizePolicy)
        self.ui_zoom_lbl.setObjectName(_fromUtf8("ui_zoom_lbl"))
        self.ui_propertiestools_dockcontents_gl.addWidget(self.ui_zoom_lbl, 9, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.ui_propertiestools_dockcontents_gl.addItem(spacerItem, 14, 0, 1, 2)
        self.ui_shapeappearance_groupbox = QtGui.QGroupBox(self.ui_propertiestools_dockcontents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.ui_shapeappearance_groupbox.sizePolicy().hasHeightForWidth())
        self.ui_shapeappearance_groupbox.setSizePolicy(sizePolicy)
        self.ui_shapeappearance_groupbox.setObjectName(_fromUtf8("ui_shapeappearance_groupbox"))
        self.ui_shape_appearance_groupbox_gl = QtGui.QGridLayout(self.ui_shapeappearance_groupbox)
        self.ui_shape_appearance_groupbox_gl.setObjectName(_fromUtf8("ui_shape_appearance_groupbox_gl"))
        self.ui_shape_setcolor_btn = QtGui.QPushButton(self.ui_shapeappearance_groupbox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_shape_setcolor_btn.sizePolicy().hasHeightForWidth())
        self.ui_shape_setcolor_btn.setSizePolicy(sizePolicy)
        self.ui_shape_setcolor_btn.setMaximumSize(QtCore.QSize(16777215, 23))
        self.ui_shape_setcolor_btn.setObjectName(_fromUtf8("ui_shape_setcolor_btn"))
        self.ui_shape_appearance_groupbox_gl.addWidget(self.ui_shape_setcolor_btn, 5, 0, 1, 1)
        self.ui_shape_settransparency_btn = QtGui.QPushButton(self.ui_shapeappearance_groupbox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_shape_settransparency_btn.sizePolicy().hasHeightForWidth())
        self.ui_shape_settransparency_btn.setSizePolicy(sizePolicy)
        self.ui_shape_settransparency_btn.setMaximumSize(QtCore.QSize(16777215, 23))
        self.ui_shape_settransparency_btn.setObjectName(_fromUtf8("ui_shape_settransparency_btn"))
        self.ui_shape_appearance_groupbox_gl.addWidget(self.ui_shape_settransparency_btn, 6, 0, 1, 1)
        self.ui_shape_transparency_dspn = QtGui.QDoubleSpinBox(self.ui_shapeappearance_groupbox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_shape_transparency_dspn.sizePolicy().hasHeightForWidth())
        self.ui_shape_transparency_dspn.setSizePolicy(sizePolicy)
        self.ui_shape_transparency_dspn.setMaximumSize(QtCore.QSize(16777215, 23))
        self.ui_shape_transparency_dspn.setMaximum(1.0)
        self.ui_shape_transparency_dspn.setSingleStep(0.1)
        self.ui_shape_transparency_dspn.setObjectName(_fromUtf8("ui_shape_transparency_dspn"))
        self.ui_shape_appearance_groupbox_gl.addWidget(self.ui_shape_transparency_dspn, 6, 1, 1, 1)
        self.ui_shape_quality_btn = QtGui.QPushButton(self.ui_shapeappearance_groupbox)
        self.ui_shape_quality_btn.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_shape_quality_btn.sizePolicy().hasHeightForWidth())
        self.ui_shape_quality_btn.setSizePolicy(sizePolicy)
        self.ui_shape_quality_btn.setMaximumSize(QtCore.QSize(16777215, 23))
        self.ui_shape_quality_btn.setObjectName(_fromUtf8("ui_shape_quality_btn"))
        self.ui_shape_appearance_groupbox_gl.addWidget(self.ui_shape_quality_btn, 7, 0, 1, 1)
        self.ui_shape_quality_dspn = QtGui.QDoubleSpinBox(self.ui_shapeappearance_groupbox)
        self.ui_shape_quality_dspn.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_shape_quality_dspn.sizePolicy().hasHeightForWidth())
        self.ui_shape_quality_dspn.setSizePolicy(sizePolicy)
        self.ui_shape_quality_dspn.setMaximumSize(QtCore.QSize(16777215, 23))
        self.ui_shape_quality_dspn.setAutoFillBackground(False)
        self.ui_shape_quality_dspn.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.ui_shape_quality_dspn.setMinimum(0.01)
        self.ui_shape_quality_dspn.setSingleStep(0.2)
        self.ui_shape_quality_dspn.setProperty("value", 1.0)
        self.ui_shape_quality_dspn.setObjectName(_fromUtf8("ui_shape_quality_dspn"))
        self.ui_shape_appearance_groupbox_gl.addWidget(self.ui_shape_quality_dspn, 7, 1, 1, 1)
        self.ui_shape_setcolor_combo = QtGui.QComboBox(self.ui_shapeappearance_groupbox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_shape_setcolor_combo.sizePolicy().hasHeightForWidth())
        self.ui_shape_setcolor_combo.setSizePolicy(sizePolicy)
        self.ui_shape_setcolor_combo.setMaximumSize(QtCore.QSize(16777215, 23))
        self.ui_shape_setcolor_combo.setObjectName(_fromUtf8("ui_shape_setcolor_combo"))
        self.ui_shape_setcolor_combo.addItem(_fromUtf8(""))
        self.ui_shape_setcolor_combo.addItem(_fromUtf8(""))
        self.ui_shape_setcolor_combo.addItem(_fromUtf8(""))
        self.ui_shape_setcolor_combo.addItem(_fromUtf8(""))
        self.ui_shape_setcolor_combo.addItem(_fromUtf8(""))
        self.ui_shape_setcolor_combo.addItem(_fromUtf8(""))
        self.ui_shape_appearance_groupbox_gl.addWidget(self.ui_shape_setcolor_combo, 5, 1, 1, 1)
        self.ui_shape_hide_btn = QtGui.QPushButton(self.ui_shapeappearance_groupbox)
        self.ui_shape_hide_btn.setMaximumSize(QtCore.QSize(16777215, 23))
        self.ui_shape_hide_btn.setObjectName(_fromUtf8("ui_shape_hide_btn"))
        self.ui_shape_appearance_groupbox_gl.addWidget(self.ui_shape_hide_btn, 3, 0, 1, 1)
        self.ui_shape_display_btn = QtGui.QPushButton(self.ui_shapeappearance_groupbox)
        self.ui_shape_display_btn.setMaximumSize(QtCore.QSize(16777215, 23))
        self.ui_shape_display_btn.setObjectName(_fromUtf8("ui_shape_display_btn"))
        self.ui_shape_appearance_groupbox_gl.addWidget(self.ui_shape_display_btn, 3, 1, 1, 1)
        self.ui_propertiestools_dockcontents_gl.addWidget(self.ui_shapeappearance_groupbox, 2, 0, 1, 2)
        self.ui_shape_transformation_groupbox = QtGui.QGroupBox(self.ui_propertiestools_dockcontents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.ui_shape_transformation_groupbox.sizePolicy().hasHeightForWidth())
        self.ui_shape_transformation_groupbox.setSizePolicy(sizePolicy)
        self.ui_shape_transformation_groupbox.setObjectName(_fromUtf8("ui_shape_transformation_groupbox"))
        self.ui_shape_transformation_groupbox_gl = QtGui.QGridLayout(self.ui_shape_transformation_groupbox)
        self.ui_shape_transformation_groupbox_gl.setObjectName(_fromUtf8("ui_shape_transformation_groupbox_gl"))
        self.ui_ydispl_lbl = QtGui.QLabel(self.ui_shape_transformation_groupbox)
        self.ui_ydispl_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.ui_ydispl_lbl.setObjectName(_fromUtf8("ui_ydispl_lbl"))
        self.ui_shape_transformation_groupbox_gl.addWidget(self.ui_ydispl_lbl, 2, 3, 1, 1)
        self.ui_shape_tetarotat_dspn = QtGui.QDoubleSpinBox(self.ui_shape_transformation_groupbox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_shape_tetarotat_dspn.sizePolicy().hasHeightForWidth())
        self.ui_shape_tetarotat_dspn.setSizePolicy(sizePolicy)
        self.ui_shape_tetarotat_dspn.setMaximumSize(QtCore.QSize(16777215, 23))
        self.ui_shape_tetarotat_dspn.setMinimum(-10000.0)
        self.ui_shape_tetarotat_dspn.setMaximum(10000.0)
        self.ui_shape_tetarotat_dspn.setSingleStep(0.1)
        self.ui_shape_tetarotat_dspn.setObjectName(_fromUtf8("ui_shape_tetarotat_dspn"))
        self.ui_shape_transformation_groupbox_gl.addWidget(self.ui_shape_tetarotat_dspn, 4, 4, 1, 1)
        self.ui_shape_rotataxis_combo = QtGui.QComboBox(self.ui_shape_transformation_groupbox)
        self.ui_shape_rotataxis_combo.setMaximumSize(QtCore.QSize(16777215, 23))
        self.ui_shape_rotataxis_combo.setObjectName(_fromUtf8("ui_shape_rotataxis_combo"))
        self.ui_shape_rotataxis_combo.addItem(_fromUtf8(""))
        self.ui_shape_rotataxis_combo.addItem(_fromUtf8(""))
        self.ui_shape_rotataxis_combo.addItem(_fromUtf8(""))
        self.ui_shape_transformation_groupbox_gl.addWidget(self.ui_shape_rotataxis_combo, 4, 6, 1, 1)
        self.ui_axisrotat_lbl = QtGui.QLabel(self.ui_shape_transformation_groupbox)
        self.ui_axisrotat_lbl.setObjectName(_fromUtf8("ui_axisrotat_lbl"))
        self.ui_shape_transformation_groupbox_gl.addWidget(self.ui_axisrotat_lbl, 4, 2, 1, 2)
        self.ui_shape_xdispl_dspn = QtGui.QDoubleSpinBox(self.ui_shape_transformation_groupbox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_shape_xdispl_dspn.sizePolicy().hasHeightForWidth())
        self.ui_shape_xdispl_dspn.setSizePolicy(sizePolicy)
        self.ui_shape_xdispl_dspn.setMaximumSize(QtCore.QSize(16777215, 23))
        self.ui_shape_xdispl_dspn.setMinimum(-10000.0)
        self.ui_shape_xdispl_dspn.setMaximum(10000.0)
        self.ui_shape_xdispl_dspn.setSingleStep(0.1)
        self.ui_shape_xdispl_dspn.setObjectName(_fromUtf8("ui_shape_xdispl_dspn"))
        self.ui_shape_transformation_groupbox_gl.addWidget(self.ui_shape_xdispl_dspn, 2, 2, 1, 1)
        self.ui_xdispl_lbl = QtGui.QLabel(self.ui_shape_transformation_groupbox)
        self.ui_xdispl_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.ui_xdispl_lbl.setObjectName(_fromUtf8("ui_xdispl_lbl"))
        self.ui_shape_transformation_groupbox_gl.addWidget(self.ui_xdispl_lbl, 2, 0, 1, 1)
        self.ui_zdispl_lbl = QtGui.QLabel(self.ui_shape_transformation_groupbox)
        self.ui_zdispl_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.ui_zdispl_lbl.setObjectName(_fromUtf8("ui_zdispl_lbl"))
        self.ui_shape_transformation_groupbox_gl.addWidget(self.ui_zdispl_lbl, 2, 5, 1, 1)
        self.ui_shape_zdispl_dspn = QtGui.QDoubleSpinBox(self.ui_shape_transformation_groupbox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_shape_zdispl_dspn.sizePolicy().hasHeightForWidth())
        self.ui_shape_zdispl_dspn.setSizePolicy(sizePolicy)
        self.ui_shape_zdispl_dspn.setMaximumSize(QtCore.QSize(16777215, 23))
        self.ui_shape_zdispl_dspn.setMinimum(-10000.0)
        self.ui_shape_zdispl_dspn.setMaximum(10000.0)
        self.ui_shape_zdispl_dspn.setSingleStep(0.1)
        self.ui_shape_zdispl_dspn.setObjectName(_fromUtf8("ui_shape_zdispl_dspn"))
        self.ui_shape_transformation_groupbox_gl.addWidget(self.ui_shape_zdispl_dspn, 2, 6, 1, 1)
        self.ui_shape_ydispl_dspn = QtGui.QDoubleSpinBox(self.ui_shape_transformation_groupbox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_shape_ydispl_dspn.sizePolicy().hasHeightForWidth())
        self.ui_shape_ydispl_dspn.setSizePolicy(sizePolicy)
        self.ui_shape_ydispl_dspn.setMaximumSize(QtCore.QSize(16777215, 23))
        self.ui_shape_ydispl_dspn.setMinimum(-10000.0)
        self.ui_shape_ydispl_dspn.setMaximum(10000.0)
        self.ui_shape_ydispl_dspn.setSingleStep(0.1)
        self.ui_shape_ydispl_dspn.setObjectName(_fromUtf8("ui_shape_ydispl_dspn"))
        self.ui_shape_transformation_groupbox_gl.addWidget(self.ui_shape_ydispl_dspn, 2, 4, 1, 1)
        self.ui_shape_settranslation_btn = QtGui.QPushButton(self.ui_shape_transformation_groupbox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_shape_settranslation_btn.sizePolicy().hasHeightForWidth())
        self.ui_shape_settranslation_btn.setSizePolicy(sizePolicy)
        self.ui_shape_settranslation_btn.setMaximumSize(QtCore.QSize(16777215, 23))
        self.ui_shape_settranslation_btn.setObjectName(_fromUtf8("ui_shape_settranslation_btn"))
        self.ui_shape_transformation_groupbox_gl.addWidget(self.ui_shape_settranslation_btn, 5, 2, 1, 6)
        self.ui_propertiestools_dockcontents_gl.addWidget(self.ui_shape_transformation_groupbox, 4, 0, 1, 2)
        self.ui_tecplot_control_groupbox = QtGui.QGroupBox(self.ui_propertiestools_dockcontents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.ui_tecplot_control_groupbox.sizePolicy().hasHeightForWidth())
        self.ui_tecplot_control_groupbox.setSizePolicy(sizePolicy)
        self.ui_tecplot_control_groupbox.setObjectName(_fromUtf8("ui_tecplot_control_groupbox"))
        self.ui_tecplot_control_groupbox_gl = QtGui.QGridLayout(self.ui_tecplot_control_groupbox)
        self.ui_tecplot_control_groupbox_gl.setMargin(5)
        self.ui_tecplot_control_groupbox_gl.setObjectName(_fromUtf8("ui_tecplot_control_groupbox_gl"))
        self.ui_tecplot_setinvisible_btn = QtGui.QPushButton(self.ui_tecplot_control_groupbox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_tecplot_setinvisible_btn.sizePolicy().hasHeightForWidth())
        self.ui_tecplot_setinvisible_btn.setSizePolicy(sizePolicy)
        self.ui_tecplot_setinvisible_btn.setMaximumSize(QtCore.QSize(16777215, 23))
        self.ui_tecplot_setinvisible_btn.setCheckable(True)
        self.ui_tecplot_setinvisible_btn.setChecked(False)
        self.ui_tecplot_setinvisible_btn.setObjectName(_fromUtf8("ui_tecplot_setinvisible_btn"))
        self.ui_tecplot_control_groupbox_gl.addWidget(self.ui_tecplot_setinvisible_btn, 0, 0, 1, 1)
        self.ui_tecplot_setneutral_btn = QtGui.QPushButton(self.ui_tecplot_control_groupbox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_tecplot_setneutral_btn.sizePolicy().hasHeightForWidth())
        self.ui_tecplot_setneutral_btn.setSizePolicy(sizePolicy)
        self.ui_tecplot_setneutral_btn.setMaximumSize(QtCore.QSize(16777215, 23))
        self.ui_tecplot_setneutral_btn.setCheckable(True)
        self.ui_tecplot_setneutral_btn.setObjectName(_fromUtf8("ui_tecplot_setneutral_btn"))
        self.ui_tecplot_control_groupbox_gl.addWidget(self.ui_tecplot_setneutral_btn, 0, 1, 1, 1)
        self.ui_tecplot_toggle_bladeprofiles_btn = QtGui.QPushButton(self.ui_tecplot_control_groupbox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_tecplot_toggle_bladeprofiles_btn.sizePolicy().hasHeightForWidth())
        self.ui_tecplot_toggle_bladeprofiles_btn.setSizePolicy(sizePolicy)
        self.ui_tecplot_toggle_bladeprofiles_btn.setMaximumSize(QtCore.QSize(16777215, 23))
        self.ui_tecplot_toggle_bladeprofiles_btn.setCheckable(True)
        self.ui_tecplot_toggle_bladeprofiles_btn.setChecked(False)
        self.ui_tecplot_toggle_bladeprofiles_btn.setObjectName(_fromUtf8("ui_tecplot_toggle_bladeprofiles_btn"))
        self.ui_tecplot_control_groupbox_gl.addWidget(self.ui_tecplot_toggle_bladeprofiles_btn, 1, 0, 1, 1)
        self.ui_tecplot_toggle_meanlines_btn = QtGui.QPushButton(self.ui_tecplot_control_groupbox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_tecplot_toggle_meanlines_btn.sizePolicy().hasHeightForWidth())
        self.ui_tecplot_toggle_meanlines_btn.setSizePolicy(sizePolicy)
        self.ui_tecplot_toggle_meanlines_btn.setMaximumSize(QtCore.QSize(16777215, 23))
        self.ui_tecplot_toggle_meanlines_btn.setCheckable(True)
        self.ui_tecplot_toggle_meanlines_btn.setChecked(False)
        self.ui_tecplot_toggle_meanlines_btn.setObjectName(_fromUtf8("ui_tecplot_toggle_meanlines_btn"))
        self.ui_tecplot_control_groupbox_gl.addWidget(self.ui_tecplot_toggle_meanlines_btn, 1, 1, 1, 1)
        self.ui_propertiestools_dockcontents_gl.addWidget(self.ui_tecplot_control_groupbox, 8, 0, 1, 2)
        self.ui_display_zoomfactor_dspn = QtGui.QDoubleSpinBox(self.ui_propertiestools_dockcontents)
        self.ui_display_zoomfactor_dspn.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_display_zoomfactor_dspn.sizePolicy().hasHeightForWidth())
        self.ui_display_zoomfactor_dspn.setSizePolicy(sizePolicy)
        self.ui_display_zoomfactor_dspn.setAutoFillBackground(False)
        self.ui_display_zoomfactor_dspn.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.ui_display_zoomfactor_dspn.setMinimum(1.01)
        self.ui_display_zoomfactor_dspn.setSingleStep(0.1)
        self.ui_display_zoomfactor_dspn.setProperty("value", 1.01)
        self.ui_display_zoomfactor_dspn.setObjectName(_fromUtf8("ui_display_zoomfactor_dspn"))
        self.ui_propertiestools_dockcontents_gl.addWidget(self.ui_display_zoomfactor_dspn, 9, 1, 1, 1)
        self.ui_propertiestools_dockW.setWidget(self.ui_propertiestools_dockcontents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.ui_propertiestools_dockW)
        self.ui_tecplotgraphics_dockW = QtGui.QDockWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_tecplotgraphics_dockW.sizePolicy().hasHeightForWidth())
        self.ui_tecplotgraphics_dockW.setSizePolicy(sizePolicy)
        self.ui_tecplotgraphics_dockW.setMinimumSize(QtCore.QSize(300, 200))
        self.ui_tecplotgraphics_dockW.setObjectName(_fromUtf8("ui_tecplotgraphics_dockW"))
        self.ui_tecplotgraphics_dockcontents = QtGui.QWidget()
        self.ui_tecplotgraphics_dockcontents.setObjectName(_fromUtf8("ui_tecplotgraphics_dockcontents"))
        self.ui_tecplotgraphics_dockcontents_vl = QtGui.QVBoxLayout(self.ui_tecplotgraphics_dockcontents)
        self.ui_tecplotgraphics_dockcontents_vl.setObjectName(_fromUtf8("ui_tecplotgraphics_dockcontents_vl"))
        self.ui_tecplot_widget = QtGui.QWidget(self.ui_tecplotgraphics_dockcontents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_tecplot_widget.sizePolicy().hasHeightForWidth())
        self.ui_tecplot_widget.setSizePolicy(sizePolicy)
        self.ui_tecplot_widget.setObjectName(_fromUtf8("ui_tecplot_widget"))
        self.ui_tecplot_widget_vl = QtGui.QVBoxLayout(self.ui_tecplot_widget)
        self.ui_tecplot_widget_vl.setObjectName(_fromUtf8("ui_tecplot_widget_vl"))
        self.ui_tecplotgraphics_dockcontents_vl.addWidget(self.ui_tecplot_widget)
        self.ui_tecplotgraphics_dockW.setWidget(self.ui_tecplotgraphics_dockcontents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.ui_tecplotgraphics_dockW)
        self.ui_tecplot_toolbar = QtGui.QToolBar(MainWindow)
        self.ui_tecplot_toolbar.setObjectName(_fromUtf8("ui_tecplot_toolbar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.ui_tecplot_toolbar)
        self.ui_settings_toolbar = QtGui.QToolBar(MainWindow)
        self.ui_settings_toolbar.setObjectName(_fromUtf8("ui_settings_toolbar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.ui_settings_toolbar)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1196, 26))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.ui_file_menu_ = QtGui.QMenu(self.menubar)
        self.ui_file_menu_.setObjectName(_fromUtf8("ui_file_menu_"))
        self.ui_edit_menu = QtGui.QMenu(self.menubar)
        self.ui_edit_menu.setObjectName(_fromUtf8("ui_edit_menu"))
        self.ui_view_menu = QtGui.QMenu(self.menubar)
        self.ui_view_menu.setObjectName(_fromUtf8("ui_view_menu"))
        self.ui_standard_view_submenu_ = QtGui.QMenu(self.ui_view_menu)
        self.ui_standard_view_submenu_.setObjectName(_fromUtf8("ui_standard_view_submenu_"))
        self.ui_draw_view_submenu_ = QtGui.QMenu(self.ui_view_menu)
        self.ui_draw_view_submenu_.setObjectName(_fromUtf8("ui_draw_view_submenu_"))
        MainWindow.setMenuBar(self.menubar)
        self.ui_file_menu = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../../.designer/backup/icons/basic/open-3.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ui_file_menu.setIcon(icon)
        self.ui_file_menu.setObjectName(_fromUtf8("ui_file_menu"))
        self.actionUndo = QtGui.QAction(MainWindow)
        self.actionUndo.setObjectName(_fromUtf8("actionUndo"))
        self.actionRedo = QtGui.QAction(MainWindow)
        self.actionRedo.setObjectName(_fromUtf8("actionRedo"))
        self.actionCut = QtGui.QAction(MainWindow)
        self.actionCut.setObjectName(_fromUtf8("actionCut"))
        self.actionCopy = QtGui.QAction(MainWindow)
        self.actionCopy.setObjectName(_fromUtf8("actionCopy"))
        self.actionPaste = QtGui.QAction(MainWindow)
        self.actionPaste.setObjectName(_fromUtf8("actionPaste"))
        self.actionPreferences = QtGui.QAction(MainWindow)
        self.actionPreferences.setObjectName(_fromUtf8("actionPreferences"))
        self.actionFront_View = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("../../.designer/backup/icons/views/front_view.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFront_View.setIcon(icon1)
        self.actionFront_View.setObjectName(_fromUtf8("actionFront_View"))
        self.actionDraw_Style = QtGui.QAction(MainWindow)
        self.actionDraw_Style.setObjectName(_fromUtf8("actionDraw_Style"))
        self.actionLa = QtGui.QAction(MainWindow)
        self.actionLa.setObjectName(_fromUtf8("actionLa"))
        self.actionLa_2 = QtGui.QAction(MainWindow)
        self.actionLa_2.setObjectName(_fromUtf8("actionLa_2"))
        self.ui_file_exit_action = QtGui.QAction(MainWindow)
        self.ui_file_exit_action.setObjectName(_fromUtf8("ui_file_exit_action"))
        self.ui_view_menu.addAction(self.ui_standard_view_submenu_.menuAction())
        self.ui_view_menu.addAction(self.ui_draw_view_submenu_.menuAction())
        self.menubar.addAction(self.ui_file_menu_.menuAction())
        self.menubar.addAction(self.ui_edit_menu.menuAction())
        self.menubar.addAction(self.ui_view_menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.ui_shape_quality_btn, self.ui_shape_quality_dspn)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.ui_file_toolbar.setWindowTitle(_translate("MainWindow", "File", None))
        self.ui_view_toolbar.setWindowTitle(_translate("MainWindow", "View", None))
        self.ui_treeview_dockW.setWindowTitle(_translate("MainWindow", "Tree View", None))
        self.ui_case_treeview.setToolTip(_translate("MainWindow", "Case List", None))
        self.ui_case_treeview.setStatusTip(_translate("MainWindow", "Case List - All loaded cases are displayed here. Select a case to modify the 3D part or the Tecplot graphics display", None))
        self.ui_subcase_list.setToolTip(_translate("MainWindow", "Sub-Shape List", None))
        self.ui_subcase_list.setStatusTip(_translate("MainWindow", "Sub-Shape List - The sub-shapes of the case loaded are displayed here. Select an item to modify it individually in Properties and Tools", None))
        self.ui_deletecase_btn.setToolTip(_translate("MainWindow", "Delete Case", None))
        self.ui_deletecase_btn.setStatusTip(_translate("MainWindow", "Delete Case - Delete one case from the list", None))
        self.ui_deletecase_btn.setText(_translate("MainWindow", "Delete Selected Case", None))
        self.ui_deletecase_btn.setShortcut(_translate("MainWindow", "Del", None))
        self.ui_propertiestools_dockW.setWindowTitle(_translate("MainWindow", "Properties and Tools", None))
        self.ui_selectedcase_edit.setToolTip(_translate("MainWindow", "Active Case", None))
        self.ui_selectedcase_edit.setStatusTip(_translate("MainWindow", "Active Case - The controls below will be applied to this case", None))
        self.ui_zoom_lbl.setToolTip(_translate("MainWindow", "Costumize visualization zoom", None))
        self.ui_zoom_lbl.setStatusTip(_translate("MainWindow", "Zoom Factor - Amount of percentage of zooming by wheel scroll", None))
        self.ui_zoom_lbl.setText(_translate("MainWindow", "Zoom Factor:", None))
        self.ui_shapeappearance_groupbox.setToolTip(_translate("MainWindow", "Shape Control", None))
        self.ui_shapeappearance_groupbox.setStatusTip(_translate("MainWindow", "Shape Control", None))
        self.ui_shapeappearance_groupbox.setTitle(_translate("MainWindow", "Shape Control", None))
        self.ui_shape_setcolor_btn.setStatusTip(_translate("MainWindow", "Set Color - Sets color to the selected sub-shape item in Sub-Shape List", None))
        self.ui_shape_setcolor_btn.setText(_translate("MainWindow", "Set Color", None))
        self.ui_shape_settransparency_btn.setToolTip(_translate("MainWindow", "Set Transparency", None))
        self.ui_shape_settransparency_btn.setStatusTip(_translate("MainWindow", "Set Transparency - Sets transparency to the selected sub-shape item in Sub-Shape List", None))
        self.ui_shape_settransparency_btn.setText(_translate("MainWindow", "Set Transp.", None))
        self.ui_shape_transparency_dspn.setToolTip(_translate("MainWindow", "Transparency value", None))
        self.ui_shape_transparency_dspn.setStatusTip(_translate("MainWindow", "Transparency - value between 0 (opaque) to 1 (fully transparent)", None))
        self.ui_shape_quality_btn.setStatusTip(_translate("MainWindow", "Set Quality - Sets quality to the selected sub-shape item in Sub-Shape List", None))
        self.ui_shape_quality_btn.setText(_translate("MainWindow", "Set Quality", None))
        self.ui_shape_quality_dspn.setToolTip(_translate("MainWindow", "Quality value", None))
        self.ui_shape_quality_dspn.setStatusTip(_translate("MainWindow", "Quality - Factor of refinement of shape. Recomended above 20", None))
        self.ui_shape_setcolor_combo.setToolTip(_translate("MainWindow", "List of Colors", None))
        self.ui_shape_setcolor_combo.setStatusTip(_translate("MainWindow", "List of Colors - List of colors available", None))
        self.ui_shape_setcolor_combo.setItemText(0, _translate("MainWindow", "Golden", None))
        self.ui_shape_setcolor_combo.setItemText(1, _translate("MainWindow", "Blue", None))
        self.ui_shape_setcolor_combo.setItemText(2, _translate("MainWindow", "Red", None))
        self.ui_shape_setcolor_combo.setItemText(3, _translate("MainWindow", "White", None))
        self.ui_shape_setcolor_combo.setItemText(4, _translate("MainWindow", "Black", None))
        self.ui_shape_setcolor_combo.setItemText(5, _translate("MainWindow", "Yellow", None))
        self.ui_shape_hide_btn.setToolTip(_translate("MainWindow", "Hide selected sub-shape", None))
        self.ui_shape_hide_btn.setStatusTip(_translate("MainWindow", "Hide Shape - Hide the selected sub-shape on the Display.", None))
        self.ui_shape_hide_btn.setText(_translate("MainWindow", "Hide Shape", None))
        self.ui_shape_hide_btn.setShortcut(_translate("MainWindow", "H", None))
        self.ui_shape_display_btn.setToolTip(_translate("MainWindow", "Display selected sub-shape", None))
        self.ui_shape_display_btn.setStatusTip(_translate("MainWindow", "Display Shape - Display the selected sub-shape on the Display.", None))
        self.ui_shape_display_btn.setText(_translate("MainWindow", "Display Shape", None))
        self.ui_shape_display_btn.setShortcut(_translate("MainWindow", "D", None))
        self.ui_shape_transformation_groupbox.setToolTip(_translate("MainWindow", "Shape Transformation", None))
        self.ui_shape_transformation_groupbox.setStatusTip(_translate("MainWindow", "Shape Transformation", None))
        self.ui_shape_transformation_groupbox.setTitle(_translate("MainWindow", "Shape Transformation", None))
        self.ui_ydispl_lbl.setText(_translate("MainWindow", "Y", None))
        self.ui_shape_tetarotat_dspn.setToolTip(_translate("MainWindow", "Rotate shape in teta value (degrees)", None))
        self.ui_shape_tetarotat_dspn.setStatusTip(_translate("MainWindow", "Rotation value of sub-shape in teta (degrees)", None))
        self.ui_shape_rotataxis_combo.setToolTip(_translate("MainWindow", "Axis of rotation", None))
        self.ui_shape_rotataxis_combo.setStatusTip(_translate("MainWindow", "Axis of rotation ", None))
        self.ui_shape_rotataxis_combo.setItemText(0, _translate("MainWindow", "X", None))
        self.ui_shape_rotataxis_combo.setItemText(1, _translate("MainWindow", "Y", None))
        self.ui_shape_rotataxis_combo.setItemText(2, _translate("MainWindow", "Z", None))
        self.ui_axisrotat_lbl.setText(_translate("MainWindow", "Rotate", None))
        self.ui_shape_xdispl_dspn.setToolTip(_translate("MainWindow", "Displace shape in x value", None))
        self.ui_shape_xdispl_dspn.setStatusTip(_translate("MainWindow", "Displacement value of sub-shape in x positive direction", None))
        self.ui_xdispl_lbl.setText(_translate("MainWindow", "X", None))
        self.ui_zdispl_lbl.setText(_translate("MainWindow", "Z", None))
        self.ui_shape_zdispl_dspn.setToolTip(_translate("MainWindow", "Displace shape in z value", None))
        self.ui_shape_zdispl_dspn.setStatusTip(_translate("MainWindow", "Displacement value of sub-shape in z positive direction", None))
        self.ui_shape_ydispl_dspn.setToolTip(_translate("MainWindow", "Displace shape in y value", None))
        self.ui_shape_ydispl_dspn.setStatusTip(_translate("MainWindow", "Displacement value of sub-shape in y positive direction", None))
        self.ui_shape_settranslation_btn.setToolTip(_translate("MainWindow", "Modifies the shape location", None))
        self.ui_shape_settranslation_btn.setStatusTip(_translate("MainWindow", "Set Transformation - Sets the transformation for the selected sub-shape item in Sub-Shape List", None))
        self.ui_shape_settranslation_btn.setText(_translate("MainWindow", "Set Transformation", None))
        self.ui_tecplot_control_groupbox.setToolTip(_translate("MainWindow", "Tecplot Control", None))
        self.ui_tecplot_control_groupbox.setStatusTip(_translate("MainWindow", "Tecplot Control", None))
        self.ui_tecplot_control_groupbox.setTitle(_translate("MainWindow", "Tecplot Control", None))
        self.ui_tecplot_setinvisible_btn.setToolTip(_translate("MainWindow", "Toggles visibility of tecplot graphics for this case", None))
        self.ui_tecplot_setinvisible_btn.setStatusTip(_translate("MainWindow", "Hide Plot - Set selected case tecplot to invisible or visible", None))
        self.ui_tecplot_setinvisible_btn.setText(_translate("MainWindow", "Toggle Case Visibility", None))
        self.ui_tecplot_setneutral_btn.setToolTip(_translate("MainWindow", "Toggles mode of tecplot graphics for this case", None))
        self.ui_tecplot_setneutral_btn.setStatusTip(_translate("MainWindow", "Set Neutral - Toggles lines to become neutral and dashed if", None))
        self.ui_tecplot_setneutral_btn.setText(_translate("MainWindow", "Toggle Case Display Mode", None))
        self.ui_tecplot_toggle_bladeprofiles_btn.setToolTip(_translate("MainWindow", "Toggles visibility of tecplot graphics for this case", None))
        self.ui_tecplot_toggle_bladeprofiles_btn.setStatusTip(_translate("MainWindow", "Hide Plot - Set selected case tecplot to invisible or visible", None))
        self.ui_tecplot_toggle_bladeprofiles_btn.setText(_translate("MainWindow", "Toggle Blade Profiles Visibility", None))
        self.ui_tecplot_toggle_meanlines_btn.setToolTip(_translate("MainWindow", "Toggles visibility of tecplot graphics for this case", None))
        self.ui_tecplot_toggle_meanlines_btn.setStatusTip(_translate("MainWindow", "Hide Plot - Set selected case tecplot to invisible or visible", None))
        self.ui_tecplot_toggle_meanlines_btn.setText(_translate("MainWindow", "Toggle Mean Lines Visibility", None))
        self.ui_display_zoomfactor_dspn.setToolTip(_translate("MainWindow", "Percentage of zooming by mouse wheel scroll", None))
        self.ui_display_zoomfactor_dspn.setStatusTip(_translate("MainWindow", "Amount of percentage of zooming by wheel scroll", None))
        self.ui_tecplotgraphics_dockW.setWindowTitle(_translate("MainWindow", "TecPlot Graphics", None))
        self.ui_tecplot_toolbar.setWindowTitle(_translate("MainWindow", "TecPlot Controls", None))
        self.ui_settings_toolbar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.ui_file_menu_.setTitle(_translate("MainWindow", "File", None))
        self.ui_edit_menu.setTitle(_translate("MainWindow", "Edit", None))
        self.ui_view_menu.setTitle(_translate("MainWindow", "View", None))
        self.ui_standard_view_submenu_.setTitle(_translate("MainWindow", "Standard Views", None))
        self.ui_draw_view_submenu_.setTitle(_translate("MainWindow", "Draw Styles", None))
        self.ui_file_menu.setText(_translate("MainWindow", "Open", None))
        self.actionUndo.setText(_translate("MainWindow", "Undo", None))
        self.actionRedo.setText(_translate("MainWindow", "Redo", None))
        self.actionCut.setText(_translate("MainWindow", "Cut", None))
        self.actionCopy.setText(_translate("MainWindow", "Copy", None))
        self.actionPaste.setText(_translate("MainWindow", "Paste", None))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences", None))
        self.actionFront_View.setText(_translate("MainWindow", "Front", None))
        self.actionDraw_Style.setText(_translate("MainWindow", "Draw Style", None))
        self.actionLa.setText(_translate("MainWindow", "la", None))
        self.actionLa_2.setText(_translate("MainWindow", "la", None))
        self.ui_file_exit_action.setText(_translate("MainWindow", "Exit", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

