
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "189ba0b2ab15e9bdc2ef5c2c8e759c86120541f6",
 "version": "0.5.14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
