
#ifndef CASADI_LINSOL_CSPARSE_EXPORT_H
#define CASADI_LINSOL_CSPARSE_EXPORT_H

#ifdef CASADI_LINSOL_CSPARSE_STATIC_DEFINE
#  define CASADI_LINSOL_CSPARSE_EXPORT
#  define CASADI_LINSOL_CSPARSE_NO_EXPORT
#else
#  ifndef CASADI_LINSOL_CSPARSE_EXPORT
#    ifdef casadi_linsol_csparse_EXPORTS
        /* We are building this library */
#      define CASADI_LINSOL_CSPARSE_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define CASADI_LINSOL_CSPARSE_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef CASADI_LINSOL_CSPARSE_NO_EXPORT
#    define CASADI_LINSOL_CSPARSE_NO_EXPORT 
#  endif
#endif

#ifndef CASADI_LINSOL_CSPARSE_DEPRECATED
#  define CASADI_LINSOL_CSPARSE_DEPRECATED 
#endif

#ifndef CASADI_LINSOL_CSPARSE_DEPRECATED_EXPORT
#  define CASADI_LINSOL_CSPARSE_DEPRECATED_EXPORT CASADI_LINSOL_CSPARSE_EXPORT CASADI_LINSOL_CSPARSE_DEPRECATED
#endif

#ifndef CASADI_LINSOL_CSPARSE_DEPRECATED_NO_EXPORT
#  define CASADI_LINSOL_CSPARSE_DEPRECATED_NO_EXPORT CASADI_LINSOL_CSPARSE_NO_EXPORT CASADI_LINSOL_CSPARSE_DEPRECATED
#endif

#define DEFINE_NO_DEPRECATED 0
#if DEFINE_NO_DEPRECATED
# define CASADI_LINSOL_CSPARSE_NO_DEPRECATED
#endif

#endif
