# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 07:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('constellation_vote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='starts',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
