
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "ea0e1fda9df0a9dd32fd24090ec832160b833cf5",
 "version": "1.0.0.post.dev394"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
