sudo: false
language: python
python:
- 2.7
- 3.6
git:
  depth: 99999
install:
- pip install tox "setuptools>=28.2"
script:
- tox
branches:
  except:
  - skeleton
deploy:
  provider: pypi
  server: https://upload.pypi.org/legacy/
  on:
    tags: true
    all_branches: true
    python: 3.6
  user: jaraco
  distributions: dists
  skip_upload_docs: true
  password:
    secure: ieliSqIQhbLtQFH9MQhh/kYY/Xjv2Bf3nyNjtjSfLjhgjKi/uzO9+UyTHV7BB4hL8NrrE+W/nAD1O+/h8CS1HUK/Lat0GoFTj8jvYyK3sDXvUxY5j3OMn0wyYq78r1ryaeB0yIC0h0DVVVUKVeBGOkGHY1uWre5XFalgZipMyz7ELwdEX37dMQJ7wLeEH2ZHV5S0Up/uDCMqP4TN3VjNhFNCoCnkDaH7O6uDY+pQ01LOJHpE95VdvgyApm7+vX5Xr9DOXkqsymArA4/97sDZVxis3jtt6stuazyHJtL9dh9Y73J4csjDbcu/4sQLnx7Yonh9i6MJgPTXZjQjF5lnCixFMMYYToWChhUJA8QsTEHQ+e3mFhmMkcCcBAodkp/INd5+sfJs/FF12mZlKiX7nQZNqwiEA8xjpM1JchHgf+7MOurQdWbCJVLd63qG1U87CgORbtXdv0xzcJ/KBMiKvXUcezBuPVU9XktJVkDQPUeV2V3Sj7RUh3MzAEwYEsyyubRcUTQzWwE2i8J1f4/6KdhSR6iBOQG8htOj2ER5/5T4OxHVZN40h1hDn9i0Zf+wULOxXIfH+FPhTm9TEgCJ9U0RSGIivR9QjFo23AGvHCXuXmLlaZK9SAeutMaCcit8yul3VoaQxoJyBXpaZoNmb27BloxcqJg6ruoQTT3lVJ4=
