apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: opendc-logstash
  namespace: {{ .Values.namespace }}
  labels:
    solution: l1_logging
    product:  logstash
    heritage: {{ .Release.Service | quote }}
    release:  {{ .Release.Name | quote }}
    chart:    "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  replicas: {{ .Values.logstash_replicas }}
  revisionHistoryLimit: 3
  strategy: {'type': 'Recreate'}
  template:
    metadata:
      labels:
        solution: l1_logging
        product:  logstash
        heritage: {{ .Release.Service | quote }}
        release:  {{ .Release.Name | quote }}
        chart:    "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      containers:
        - name:  opendc-logstash
          image: {{ .Values.logstash_image }}:{{ .Values.logstash_tag }}
          imagePullPolicy: {{ default "IfNotPresent" .Values.pullPolicy }}
          ports:
            - name:          ui
              containerPort: 5601
              protocol:      TCP
          env:          
            - name:  "ELASTICSEARCH_URL"
              value: "http://opendc-elasticsearch:9200"
          resources:
            limits:
              cpu:    200m
              memory: 200Mi
            requests:
              cpu:    200m
              memory: 200Mi
          volumeMounts:
            - name:      opendc-logstash
                mountPath: /etc/logstash/
