# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processengine', '0005_auto_20170430_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execution',
            name='begins',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='execution',
            name='ended',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
