# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 01:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_results', '0001_initial'),
        ('processengine', '0006_auto_20170430_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='execution',
            name='ended',
        ),
        migrations.AddField(
            model_name='execution',
            name='result',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_results.TaskResult'),
        ),
    ]
