# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetadapter', '0001_initial'),
        ('processengine', '0007_auto_20170501_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='input_parameters',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='input_parameters', to='assetadapter.Property'),
        ),
        migrations.AddField(
            model_name='process',
            name='output_parameters',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='output_parameters', to='assetadapter.Property'),
        ),
    ]
