---
# Generate Kubernetes certificates
- name: certificates | Set fact for k8sdc masters FQDN 
  set_fact:
    k8sdc_fqdn: "kubernetes.default.svc.{{ solutions.cs1_cluster_services.domain }}"

- name: certificates | Set fact for k8sdc masters DNS values
  set_fact:
    k8sdc_master_dns_values: >-
      kubernetes,
      kubernetes.default,
      kubernetes.default.svc,
      {%- for apiserver in groups['k8sdc-masters'] -%}
        {{ apiserver }},
      {%- endfor -%}
      {{ k8sdc_fqdn }}

- name: certificates | Convert fact for k8sdc masters DNS values to a list
  set_fact:
    k8sdc_master_dns_values: >-
      {{ k8sdc_master_dns_values.split(',') | map('regex_replace', ' ', '') | list }}

- name: certificates | Set fact for k8sdc masters IP addresses
  set_fact:
    k8sdc_master_ip_values: >-
      10.254.0.1,
      {%- for apiserver in groups['k8sdc-masters'] -%}
      {{ hostvars[apiserver]['ansible_' + interface].ipv4.address }}
      {%- if not loop.last -%},{%- endif -%}
      {%- endfor -%}

- name: certificates | Convert fact for k8sdc masters IP addresses to a list
  set_fact:
    k8sdc_master_ip_values: >-
      {{ k8sdc_master_ip_values.split(',') | list }}

- name: certificates | Generate certificates
  include: ../../k8sdc-ca/tasks/certificate.yaml
  vars:
    cn:         "{{ item.cn }}"
    cert_name:  "{{ item.cert_name }}"
    dns_values: "{{ item.dns_values }}"
    ip_values:  "{{ item.ip_values }}"
  with_items:
    - { cn:         'kube-apiserver', 
        cert_name:  'kube_apiserver', 
        dns_values: "{{ k8sdc_master_dns_values }}", 
        ip_values:  "{{ k8sdc_master_ip_values }}" }
    - { cn:         'kube-controller-manager', 
        cert_name:  'kube_controller_manager', 
        dns_values: "{{ k8sdc_master_dns_values }}", 
        ip_values:  "{{ k8sdc_master_ip_values }}" }
  delegate_to: "{{ groups['k8sdc-ca'][0] }}"
  run_once: yes







