---
- name: Fetch VPC Subnet Facts
  ec2_vpc_subnet_facts:
    filters:
      "tag:Name": "{{ vpc.name }}"
    region: "{{ vpc.region }}"
  register: subnet_facts

- set_fact:
    subnet_id: "{{ item.id }}"
  with_items: "{{subnet_facts.subnets}}"
  when: item.tags.Name == "{{ vpc.subnet.name }}"
