from setuptools import setup

setup(name='qbx',
      author='Youze Tang',
      url='https://github.com/qbtrade/qbx',
      author_email='tangyouze@gmail.com',
      packages=['qbx'],
      version='0.0.0',
      install_requires=[
          'elasticsearch',
          'pandas',
          'pytz',
          'pyyaml',
          'sqlalchemy',
          'requests',
          'aiohttp==1.3.5',
          'fluent-logger',
          'oss2',
          'jinja2',
          'autobahn==0.17.1',
          'docopt',
          'datadog',
          'asyncio_redis',
          'colorama',
          'influxdb',
          'arrow',
          'redis',
          'psutil',
          'numpy',
          'lxml',
          'oss2',
          'pymongo',
          'bearychat-py',
          'fluent-logger',
          'tushare',
      ],
      zip_safe=False,
      )
