
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-04-04T05:47:10+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "99132047ffbdc72572d14c868ca01d4e97368843",
 "version": "2.0.0a3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
