# -*- coding: utf-8 -*-
# Copyright (c) 2015, PyRETIS Development Team.
# Distributed under the LGPLv3 License. See LICENSE for more info.
"""Version information for PyRETIS.

This file is generated by PyRETIS (``setup_version.py``)
"""
SHORT_VERSION = '0.9.0.dev2'
VERSION = '0.9.0.dev2'
FULL_VERSION = '0.9.0.dev2'
GIT_REVISION = 'f6c06bd31d65e6528c3988e96416b7c7dee5605d'
GIT_VERSION = '0.9.0.dev2+f6c06bd'
RELEASE = False

if not RELEASE:
    VERSION = GIT_VERSION
