---
#global settings
my_server_id: 100
replica_batch_size: 1000
batch_retention: '1 day'
copy_max_memory: 300M
my_database:  db_replica
pg_database: db_replication
copy_mode: 'file' 
#copy_mode: 'direct'
source_name: 'default'
dest_schema: 'my_schema'



#seconds between each replica loop
sleep_loop: 10 

#Pause the replica for the given amount of seconds if a reindex process is found
pause_on_reindex: Yes
sleep_on_reindex: 30

#list the application names which are supposed to reindex the database
reindex_app_names:
    - 'reindexdb'
    - 'my_custom_reindex'

hexify: 
    - 'blob'
    - 'tinyblob'
    - 'mediumblob'
    - 'longblob'
    - 'binary'

 
pid_dir: '~/.pg_chameleon/pid/'


log_dir: '~/.pg_chameleon/logs/'
log_level: 'debug'
log_dest: 'stdout'
log_append: True
#log_dest: 'file'
#log_level: 'info'
#log_level: 'debug'


#mysql connection's charset. 
my_charset: 'utf8'
#postgresql connection's charset. 
pg_charset: 'utf8'
#include tables only
tables_limit:
    

#mysql slave setup
mysql_conn:
    host: localhost
    port: 3306
    user: replication_username
    passwd: never_commit_passwords

#postgres connection
pg_conn:
    host: localhost
    port: 5432
    user: replication_username
    password: never_commit_passwords
 
 #email configuration
email_config: 
    smtp_use_password: Yes
    smtp_host: 'smtp.foo.bar'
    smtp_port: 587
    smtp_username: login@foo.bar
    smtp_password: never_commit_passwords
    smtp_use_tls: Yes
    email_from: pgchameleon@foo.bar
    recipients:
        - alert@foo.bar
