
- instance:
    input:
        name: genetalk_db_machine 
        image_id: ami-fce3c696 
        keyname: gcta-us-east-1-access-key   
        subnet_id:
            value: subnet-3698831c 
        number: 1
        instance_type: m4.large 
        security_group_ids:
            value: [sg-706ed00a]
        tags:
            - tag:
                key: Name
                value: genetalk_test_instance 

        spot:
            price: 0.1
            wait_until_complete: 1
            #           availability_zone_group: ggg
            #   duration: 6

#    vpc:
#       from_config: ./libaws/demo/vpc_config.yaml
#    
#    keypair:
#        key: genetalk_access_key   
#        delete_exists: True
#
    volumes:
       - volume:
           size: 20
           name: /dev/xvdb

