# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (3, 0, 0):
    new_instancemethod = lambda func, inst, cls: _port.SWIG_PyInstanceMethod_New(func)
else:
    from new import instancemethod as new_instancemethod
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_port')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_port')
    _port = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_port', [dirname(__file__)])
        except ImportError:
            import _port
            return _port
        try:
            _mod = imp.load_module('_port', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _port = swig_import_helper()
    del swig_import_helper
else:
    import _port
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        object.__setattr__(self, name, value)
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_method(set):
    def set_attr(self, name, value):
        if (name == "thisown"):
            return self.this.own(value)
        if hasattr(self, name) or (name == "this"):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add attributes to %s" % self)
    return set_attr


TRUE = _port.TRUE
FALSE = _port.FALSE
GP_PORT_SERIAL_PARITY_OFF = _port.GP_PORT_SERIAL_PARITY_OFF
GP_PORT_SERIAL_PARITY_EVEN = _port.GP_PORT_SERIAL_PARITY_EVEN
GP_PORT_SERIAL_PARITY_ODD = _port.GP_PORT_SERIAL_PARITY_ODD
GP_PORT_MAX_BUF_LEN = _port.GP_PORT_MAX_BUF_LEN
GP_PORT_USB_ENDPOINT_IN = _port.GP_PORT_USB_ENDPOINT_IN
GP_PORT_USB_ENDPOINT_OUT = _port.GP_PORT_USB_ENDPOINT_OUT
GP_PORT_USB_ENDPOINT_INT = _port.GP_PORT_USB_ENDPOINT_INT
class GPPort(object):
    """Proxy of C _GPPort struct."""

    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self):
        """__init__(self) -> GPPort"""
        _port.GPPort_swiginit(self, _port.new_GPPort())
    __swig_destroy__ = _port.delete_GPPort
GPPort_swigregister = _port.GPPort_swigregister
GPPort_swigregister(GPPort)


def gp_port_new():
    """
    gp_port_new() -> int

    See also: gphoto2.GPPort
    """
    return _port.gp_port_new()
GP_PIN_RTS = _port.GP_PIN_RTS
GP_PIN_DTR = _port.GP_PIN_DTR
GP_PIN_CTS = _port.GP_PIN_CTS
GP_PIN_DSR = _port.GP_PIN_DSR
GP_PIN_CD = _port.GP_PIN_CD
GP_PIN_RING = _port.GP_PIN_RING
GP_LEVEL_LOW = _port.GP_LEVEL_LOW
GP_LEVEL_HIGH = _port.GP_LEVEL_HIGH


