
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "3c06994825f7f7dcb41677c1d77877db22e48051",
 "version": "0.10.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
