
#ifndef CASADI_CONIC_CLP_EXPORT_H
#define CASADI_CONIC_CLP_EXPORT_H

#ifdef CASADI_CONIC_CLP_STATIC_DEFINE
#  define CASADI_CONIC_CLP_EXPORT
#  define CASADI_CONIC_CLP_NO_EXPORT
#else
#  ifndef CASADI_CONIC_CLP_EXPORT
#    ifdef casadi_conic_clp_EXPORTS
        /* We are building this library */
#      define CASADI_CONIC_CLP_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define CASADI_CONIC_CLP_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef CASADI_CONIC_CLP_NO_EXPORT
#    define CASADI_CONIC_CLP_NO_EXPORT 
#  endif
#endif

#ifndef CASADI_CONIC_CLP_DEPRECATED
#  define CASADI_CONIC_CLP_DEPRECATED 
#endif

#ifndef CASADI_CONIC_CLP_DEPRECATED_EXPORT
#  define CASADI_CONIC_CLP_DEPRECATED_EXPORT CASADI_CONIC_CLP_EXPORT CASADI_CONIC_CLP_DEPRECATED
#endif

#ifndef CASADI_CONIC_CLP_DEPRECATED_NO_EXPORT
#  define CASADI_CONIC_CLP_DEPRECATED_NO_EXPORT CASADI_CONIC_CLP_NO_EXPORT CASADI_CONIC_CLP_DEPRECATED
#endif

#define DEFINE_NO_DEPRECATED 0
#if DEFINE_NO_DEPRECATED
# define CASADI_CONIC_CLP_NO_DEPRECATED
#endif

#endif
