
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "42252afd009b31830ff3fc709f0d50b1ee7dd5bc",
 "version": "0.5.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
