# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omCmsMain', '0009_auto_20170322_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitemaininfo',
            name='displaySlideShow',
            field=models.BooleanField(default=True),
        ),
    ]
