# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omCmsMain', '0038_auto_20170411_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryitem',
            name='showOnTopMenu',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='categoryitem',
            name='itemReadMore',
            field=models.CharField(blank=True, default='Ver +', max_length=50, null=True, verbose_name="Label to 'Read More' buttom"),
        ),
    ]
