
#ifndef CASADI_DPLE_SLICOT_EXPORT_H
#define CASADI_DPLE_SLICOT_EXPORT_H

#ifdef CASADI_DPLE_SLICOT_STATIC_DEFINE
#  define CASADI_DPLE_SLICOT_EXPORT
#  define CASADI_DPLE_SLICOT_NO_EXPORT
#else
#  ifndef CASADI_DPLE_SLICOT_EXPORT
#    ifdef casadi_dple_slicot_EXPORTS
        /* We are building this library */
#      define CASADI_DPLE_SLICOT_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define CASADI_DPLE_SLICOT_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef CASADI_DPLE_SLICOT_NO_EXPORT
#    define CASADI_DPLE_SLICOT_NO_EXPORT 
#  endif
#endif

#ifndef CASADI_DPLE_SLICOT_DEPRECATED
#  define CASADI_DPLE_SLICOT_DEPRECATED 
#endif

#ifndef CASADI_DPLE_SLICOT_DEPRECATED_EXPORT
#  define CASADI_DPLE_SLICOT_DEPRECATED_EXPORT CASADI_DPLE_SLICOT_EXPORT CASADI_DPLE_SLICOT_DEPRECATED
#endif

#ifndef CASADI_DPLE_SLICOT_DEPRECATED_NO_EXPORT
#  define CASADI_DPLE_SLICOT_DEPRECATED_NO_EXPORT CASADI_DPLE_SLICOT_NO_EXPORT CASADI_DPLE_SLICOT_DEPRECATED
#endif

#define DEFINE_NO_DEPRECATED 0
#if DEFINE_NO_DEPRECATED
# define CASADI_DPLE_SLICOT_NO_DEPRECATED
#endif

#endif
