
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "a9b7fbc4a168b5d16970d16575a6a75a737432a5",
 "version": "0.5.15"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
