
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "ac310a3b8c4f4c3ac84ef8639233f3e22cf2d0ec",
 "version": "2.0.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
