# This file is generated by /home/hassan/scm/python/scikit-misc/setup.py
# It contains system_info results at the time of building this package.
__all__ = ["get_info","show"]

atlas_3_10_blas_info={}
blas_mkl_info={}
openblas_info={}
blas_info={'library_dirs': ['/usr/lib64'], 'libraries': ['blas', 'blas']}
atlas_blas_info={}
atlas_3_10_blas_threads_info={}
blas_opt_info={'library_dirs': ['/usr/lib64'], 'define_macros': [('NO_ATLAS_INFO', 1)], 'libraries': ['blas', 'blas']}
atlas_blas_threads_info={}

def get_info(name):
    g = globals()
    return g.get(name, g.get(name + "_info", {}))

def show():
    for name,info_dict in globals().items():
        if name[0] == "_" or type(info_dict) is not type({}): continue
        print(name + ":")
        if not info_dict:
            print("  NOT AVAILABLE")
        for k,v in info_dict.items():
            v = str(v)
            if k == "sources" and len(v) > 200:
                v = v[:60] + " ...\n... " + v[-60:]
            print("    %s = %s" % (k,v))
    