dist: trusty
language: python
cache:
  pip: true
  directories:
  - packages
  - tests/cache
  - $HOME/Library/Caches/Homebrew

matrix:
  include:
    - os: linux
      sudo: required
      language: python
      python: 3.4
    - os: linux
      sudo: required
      language: python
      python: 3.5
    - os: linux
      sudo: required
      language: python
      python: 3.6
    - os: osx
      osx_image: xcode8
      language: generic
      env:
        - secure: "hsf6MT+n2x3OiDM2fQyJZdV0/PWYmv81LdVqC6cfnHBE/8N3DloJRqQ7WfO14TxhiK9PEC7MpyCj0lSabUHEO7gSH6Vks6I1asoSkt8S9/bSMlhT4hei+pwVpeGEiU5xHVATNjY+D919VC3IFvc3XmjT74h/2SLhaZ+jhEmDggM="

before_cache:
- rm -f $HOME/.cache/pip/log/debug.log

before_install: |
  if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    bash .travis/linux_before_install.sh
  elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    bash .travis/osx_before_install.sh
  fi

install:
- pip3 install .
- pip3 install -r requirements.txt -r test_requirements.txt

script:
- mv ocrmypdf dont_import_this_ocrmypdf
- pytest
- mv dont_import_this_ocrmypdf ocrmypdf

deploy:
  # release for main pypi
- provider: pypi
  user: ocrmypdf-travis
  password:
    secure: "DTFOmmNL6olA0+yXvp4u9jXZlZeqrJsJ0526jzqf4a3gZ6jnGTq5UI6WzRsslSyoMMfXKtHQebqHM6ogSgCZinyZ3ufHJo8fn9brxbEc2gsiWkbj5o3bGwdWMT1vNNE7XW0VCpw87rZ1EEwjl4FJHFudMlPR1yfU5+uq0k0PACo="
  distributions: "sdist bdist_wheel"
  on:
    branch: master
    tags: true
    condition: $TRAVIS_PYTHON_VERSION == "3.6" && $TRAVIS_OS_NAME == "linux"
  skip_upload_docs: true

  # test pypi
- provider: pypi
  server: https://testpypi.python.org/pypi
  user: ocrmypdf-travis
  password:
    secure: "DTFOmmNL6olA0+yXvp4u9jXZlZeqrJsJ0526jzqf4a3gZ6jnGTq5UI6WzRsslSyoMMfXKtHQebqHM6ogSgCZinyZ3ufHJo8fn9brxbEc2gsiWkbj5o3bGwdWMT1vNNE7XW0VCpw87rZ1EEwjl4FJHFudMlPR1yfU5+uq0k0PACo="
  distributions: "sdist"
  on:
    branch: develop
    tags: false
    condition: $TRAVIS_OS_NAME == "osx"
  skip_upload_docs: true

after_deploy:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then bash .travis/osx_brew.sh ; fi