sudo: false
language: python
cache: pip
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
env:
  - TOXENV="django14"
  - TOXENV="django15"
  - TOXENV="django16"
  - TOXENV="django17"
  - TOXENV="django18"
  - TOXENV="django19"
  - TOXENV="django110"
  - TOXENV="django111"
  - TOXENV="djangodev"

matrix:
  fast_finish: true
  exclude:
    - python: "3.6"
      env: TOXENV="django14"
    - python: "3.6"
      env: TOXENV="django15"
    - python: "3.6"
      env: TOXENV="django16"
    - python: "3.6"
      env: TOXENV="django17"
    - python: "3.6"
      env: TOXENV="django18"
    - python: "3.6"
      env: TOXENV="django19"
    - python: "3.6"
      env: TOXENV="django110"

    - python: "3.5"
      env: TOXENV="django14"
    - python: "3.5"
      env: TOXENV="django15"
    - python: "3.5"
      env: TOXENV="django16"
    - python: "3.5"
      env: TOXENV="django17"

    - python: "3.4"
      env: TOXENV="django14"
    - python: "3.4"
      env: TOXENV="django19"
    - python: "3.4"
      env: TOXENV="django110"
    - python: "3.4"
      env: TOXENV="django111"

    - python: "3.3"
      env: TOXENV="django14"
    - python: "3.3"
      env: TOXENV="django19"
    - python: "3.3"
      env: TOXENV="django110"
    - python: "3.3"
      env: TOXENV="django111"
    - python: "3.3"
      env: TOXENV="djangodev"

    - python: "3.2"
      env: TOXENV="django14"
    - python: "3.2"
      env: TOXENV="django19"
    - python: "3.2"
      env: TOXENV="django110"
    - python: "3.2"
      env: TOXENV="django111"
    - python: "3.2"
      env: TOXENV="djangodev"

    - python: "2.6"
      env: TOXENV="django17"
    - python: "2.6"
      env: TOXENV="django18"
    - python: "2.6"
      env: TOXENV="django19"
    - python: "2.6"
      env: TOXENV="django110"
    - python: "2.6"
      env: TOXENV="django111"
    - python: "2.6"
      env: TOXENV="djangodev"

  allow_failures:
    - env: TOXENV="djangodev"

before_install:
- pip install codecov coverage==3.6 tox

script:
  - tox

after_success:
- coverage xml -i
- codecov

branches:
  only:
    - master
