package:
  name: easyaccess
  version: "1.3.1"

source:
  fn: easyaccess-1.3.1.tar.gz
  md5: 52eab3638697249f7cfda79fdd665bab
  url: https://pypi.python.org/packages/c3/47/39a31eb7e3c1cc5b34a7cbd42ad6f881a810fd9e0598319404222a137599/easyaccess-1.3.1.tar.gz
  

build:
  number: 0


requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - future
    - termcolor
    - fitsio >=0.9.8
    - pandas >=0.14
    - oracle-instantclient
    - cx_oracle

test:
  # Python imports
  imports:
    - easyaccess

about:
  home: https://github.com/mgckind/easyaccess
  license: University of Illinois/NCSA Open Source License
  summary: 'Python command line interpreter to access DES Oracle database'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
