__version__ = "0.8.1"
__git_commiter_name__ = "Itai Shirav"
__git_commiter_email__ = "itais@infinidat.com"
__git_branch__ = u'(HEAD detached at v0.8.1)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = 'f9bf8042b6ed733e64ed50bff31dcd3024908a8e'
__git_head_subject__ = u'Finished Release v0.8.1'
__git_head_message__ = u''
__git_dirty_diff__ = u''
__git_commit_date__ = '2017-04-05 18:38:23'
