networks:
  default:
    external:
      name: vd
services:
  locomotive:
    image: akretion/voodoo-ruby:latest
    volumes:
    - .:/workspace
    links:
     - db
  db:
     image: mongo:3
     volumes:
       - .db:/data/db
version: '2'
