# from netbase import world, net
# print(net.states[0])
# print(net.states[0].description)
# print(net.states.descriptions)
# print(net.states[0].type)
# print(net.states[0].id)
# # print(net.states[0].subclasses)
# print(net.states[0].short)
# # print(net.california.open())
# # print(net.united_states_.edges.to_s())
# # print(net.united_states_.predicates)
# # print(net.united_states_.ofs)
# # print(alle.weapons)
# # print(net.north_america.countries)
# # print(net.north_america.predicates)
# # print(net.north_america.parts)
# # print(net.north_america.rocky_mountains_)
# print(net.rocky_mountains_.list)
#
# # print(net.north_america.states)
#
# # print(alle.insects)
# # print(net.id_10017)
# # print(net.types('country').id)
# #
# print(net.Germany.name)
# print(net.Germany.capital)
# # print(net.Germany.edges)
# # print(net.Germany.predicates)
# print(net.Germany.type)
# print(net.Germany.saint)
# print(net.Germany.borders)
# print(net.Germany.time_zone)
# print(net.Germany.country_code)
# # print(net.Germany.image)
# print(net.Germany.flag.image)
#
# # print(net.Germany.born.edges)
#
# # print(net.all.US)
# # print(net.united_states_of_america)
# # ps = str(net.winter.Part_of)
# # print(ps)
# print(world.california.show())
# print(world.california.parts)
# print(world.california.parts.count())
# print(world.california.parts.like("park"))
# print(world.california.parks)
# print(world.california.lakes)
#
# # print(world.california.parts.grep("river").unique())
#
# # print(world.california.open())
# # print(world.california.all.parks)
# # print(world.california.show_compact())
# # print(net.winter.show_compact())
# # print(world.california.synonym.id)
# # print(net.c)
# # print(net.countries)
# # print(net.weapons)
# # print(net.states)
