# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-11 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsonattrs', '0005_remove_monolingual_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='default',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
