- name: wait for Jenkins to start up
  become: false
  wait_for:
    port: "{{ https_enabled | ternary(443, 80) }}"
    state: started
    delay: 15

# TODO: When the Ansible SSH user is root, why is the jar file saved to /root
# and not /var/lib/jenkins?
- name: download jenkins CLI
  get_url:
    url: "{{ https_enabled | ternary('https', 'http') }}://localhost/jnlpJars/jenkins-cli.jar"
    dest: "{{ jenkins_home }}/jenkins-cli.jar"
    force: true
    validate_certs: false
  become_user: jenkins

- name: configure CLI users appropriately
  become: false
  jenkins_cli_user:
    jenkins_home: "{{ jenkins_home }}"
    key_file: "{{ ansible_user_dir }}/.ssh/id_rsa.pub"
