
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-04-21T17:10:03-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "b915dce1237b9a6c3914373138f0ddb1206bb551",
 "version": "221.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
