
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "b70ad32dd0e736e650348582168bda2b05e2d8b2",
 "version": "0.3.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
