
# This file was generated by 'versioneer.py' from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.2.5'
version_full = '341513f403dee0b2c49e9630c86f0483c0d2d359'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

