# -*- coding: utf-8 -*-


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_WBlower(object):
    def setupUi(self, WBlower):
        WBlower.setObjectName("WBlower")
        WBlower.resize(615, 437)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/blower"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        WBlower.setWindowIcon(icon)
        WBlower.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.verticalLayout = QtWidgets.QVBoxLayout(WBlower)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(WBlower)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.tempLabel = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(40)
        self.tempLabel.setFont(font)
        self.tempLabel.setObjectName("tempLabel")
        self.horizontalLayout_2.addWidget(self.tempLabel)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_7.addWidget(self.label_10)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.currentLabel = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(20)
        self.currentLabel.setFont(font)
        self.currentLabel.setObjectName("currentLabel")
        self.horizontalLayout_7.addWidget(self.currentLabel)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.targetSpinBox = QtWidgets.QDoubleSpinBox(self.tab)
        self.targetSpinBox.setSuffix("")
        self.targetSpinBox.setDecimals(1)
        self.targetSpinBox.setMinimum(25.0)
        self.targetSpinBox.setMaximum(1000.0)
        self.targetSpinBox.setObjectName("targetSpinBox")
        self.horizontalLayout_4.addWidget(self.targetSpinBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.rampSpinBox = QtWidgets.QDoubleSpinBox(self.tab)
        self.rampSpinBox.setSuffix("")
        self.rampSpinBox.setDecimals(1)
        self.rampSpinBox.setMinimum(0.0)
        self.rampSpinBox.setMaximum(1000.0)
        self.rampSpinBox.setObjectName("rampSpinBox")
        self.horizontalLayout_3.addWidget(self.rampSpinBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.runButton = QtWidgets.QPushButton(self.tab)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/run"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.runButton.setIcon(icon1)
        self.runButton.setObjectName("runButton")
        self.horizontalLayout_5.addWidget(self.runButton)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.toSeqButton = QtWidgets.QPushButton(self.tab)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/macro"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toSeqButton.setIcon(icon2)
        self.toSeqButton.setObjectName("toSeqButton")
        self.horizontalLayout_5.addWidget(self.toSeqButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.plotView = PlotWidget(self.tab_2)
        self.plotView.setObjectName("plotView")
        self.verticalLayout_3.addWidget(self.plotView)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.startPlotButton = QtWidgets.QPushButton(self.tab_2)
        self.startPlotButton.setIcon(icon1)
        self.startPlotButton.setObjectName("startPlotButton")
        self.horizontalLayout_6.addWidget(self.startPlotButton)
        self.clearPlotButton = QtWidgets.QPushButton(self.tab_2)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/clear"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clearPlotButton.setIcon(icon3)
        self.clearPlotButton.setObjectName("clearPlotButton")
        self.horizontalLayout_6.addWidget(self.clearPlotButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.formLayout = QtWidgets.QFormLayout(self.tab_3)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label_4 = QtWidgets.QLabel(self.tab_3)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.hostEdit = QtWidgets.QLineEdit(self.tab_3)
        self.hostEdit.setObjectName("hostEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.hostEdit)
        self.label_5 = QtWidgets.QLabel(self.tab_3)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.sessionEdit = QtWidgets.QLineEdit(self.tab_3)
        self.sessionEdit.setObjectName("sessionEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.sessionEdit)
        self.label_6 = QtWidgets.QLabel(self.tab_3)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.motorEdit = QtWidgets.QLineEdit(self.tab_3)
        self.motorEdit.setObjectName("motorEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.motorEdit)
        self.label_7 = QtWidgets.QLabel(self.tab_3)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.counterEdit = QtWidgets.QLineEdit(self.tab_3)
        self.counterEdit.setObjectName("counterEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.counterEdit)
        self.rampEdit = QtWidgets.QLineEdit(self.tab_3)
        self.rampEdit.setObjectName("rampEdit")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.rampEdit)
        spacerItem6 = QtWidgets.QSpacerItem(20, 119, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(8, QtWidgets.QFormLayout.FieldRole, spacerItem6)
        self.label_8 = QtWidgets.QLabel(self.tab_3)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.errorEdit = QtWidgets.QLineEdit(self.tab_3)
        self.errorEdit.setObjectName("errorEdit")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.errorEdit)
        self.label_9 = QtWidgets.QLabel(self.tab_3)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.tabWidget.addTab(self.tab_3, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.connectButton = QtWidgets.QPushButton(WBlower)
        self.connectButton.setObjectName("connectButton")
        self.horizontalLayout.addWidget(self.connectButton)
        self.disconnectButton = QtWidgets.QPushButton(WBlower)
        self.disconnectButton.setObjectName("disconnectButton")
        self.horizontalLayout.addWidget(self.disconnectButton)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem7)
        self.closeButton = QtWidgets.QPushButton(WBlower)
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout.addWidget(self.closeButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(WBlower)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(WBlower)

    def retranslateUi(self, WBlower):
        _translate = QtCore.QCoreApplication.translate
        WBlower.setWindowTitle(_translate("WBlower", "Blower status"))
        self.label.setText(_translate("WBlower", "Temperature"))
        self.tempLabel.setText(_translate("WBlower", "<html><head/><body><p>0 &deg;C</p></body></html>"))
        self.label_10.setText(_translate("WBlower", "Current target and ramp"))
        self.currentLabel.setText(_translate("WBlower", "<html><head/><body><p>0 &deg;C</p></body></html>"))
        self.label_2.setText(_translate("WBlower", "Target temperature"))
        self.label_3.setText(_translate("WBlower", "Temperature ramp (deg/min)"))
        self.runButton.setText(_translate("WBlower", "Run"))
        self.toSeqButton.setText(_translate("WBlower", "To Sequence"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("WBlower", "Control"))
        self.startPlotButton.setText(_translate("WBlower", "Start"))
        self.clearPlotButton.setText(_translate("WBlower", "Clear"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("WBlower", "Plot"))
        self.label_4.setText(_translate("WBlower", "Host"))
        self.label_5.setText(_translate("WBlower", "Session"))
        self.label_6.setText(_translate("WBlower", "Motor"))
        self.label_7.setText(_translate("WBlower", "Counter"))
        self.label_8.setText(_translate("WBlower", "Ramp"))
        self.label_9.setText(_translate("WBlower", "Error"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("WBlower", "Settings"))
        self.connectButton.setText(_translate("WBlower", "Connect"))
        self.disconnectButton.setText(_translate("WBlower", "Disconnect"))
        self.closeButton.setText(_translate("WBlower", "Close"))

from pyqtgraph import PlotWidget
from . import resources_rc

