# -*- coding: utf-8 -*-


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_WLakeshore(object):
    def setupUi(self, WLakeshore):
        WLakeshore.setObjectName("WLakeshore")
        WLakeshore.resize(810, 551)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/lakeshore"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        WLakeshore.setWindowIcon(icon)
        WLakeshore.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(WLakeshore)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.plotView = PlotWidget(WLakeshore)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotView.sizePolicy().hasHeightForWidth())
        self.plotView.setSizePolicy(sizePolicy)
        self.plotView.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.plotView.setObjectName("plotView")
        self.horizontalLayout_10.addWidget(self.plotView)
        self.groupBox = QtWidgets.QGroupBox(WLakeshore)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.ipLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.ipLineEdit.setObjectName("ipLineEdit")
        self.horizontalLayout_4.addWidget(self.ipLineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_11.addWidget(self.label_8)
        self.outputComboBox = QtWidgets.QComboBox(self.groupBox)
        self.outputComboBox.setObjectName("outputComboBox")
        self.outputComboBox.addItem("")
        self.outputComboBox.addItem("")
        self.horizontalLayout_11.addWidget(self.outputComboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_12.addWidget(self.label_9)
        self.sensorComboBox = QtWidgets.QComboBox(self.groupBox)
        self.sensorComboBox.setObjectName("sensorComboBox")
        self.sensorComboBox.addItem("")
        self.sensorComboBox.addItem("")
        self.sensorComboBox.addItem("")
        self.sensorComboBox.addItem("")
        self.horizontalLayout_12.addWidget(self.sensorComboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.pSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.pSpinBox.setDecimals(1)
        self.pSpinBox.setMinimum(0.1)
        self.pSpinBox.setMaximum(1000.0)
        self.pSpinBox.setProperty("value", 100.0)
        self.pSpinBox.setObjectName("pSpinBox")
        self.horizontalLayout_3.addWidget(self.pSpinBox)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.iSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.iSpinBox.setDecimals(1)
        self.iSpinBox.setMinimum(0.1)
        self.iSpinBox.setMaximum(1000.0)
        self.iSpinBox.setProperty("value", 30.0)
        self.iSpinBox.setObjectName("iSpinBox")
        self.horizontalLayout_2.addWidget(self.iSpinBox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.dSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.dSpinBox.setDecimals(1)
        self.dSpinBox.setMaximum(200.0)
        self.dSpinBox.setObjectName("dSpinBox")
        self.horizontalLayout.addWidget(self.dSpinBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.moutSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.moutSpinBox.setPrefix("")
        self.moutSpinBox.setMaximum(100.0)
        self.moutSpinBox.setObjectName("moutSpinBox")
        self.horizontalLayout_5.addWidget(self.moutSpinBox)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_7.addWidget(self.label_6)
        self.rangeComboBox = QtWidgets.QComboBox(self.groupBox)
        self.rangeComboBox.setObjectName("rangeComboBox")
        self.rangeComboBox.addItem("")
        self.rangeComboBox.addItem("")
        self.rangeComboBox.addItem("")
        self.rangeComboBox.addItem("")
        self.horizontalLayout_7.addWidget(self.rangeComboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        self.setpSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.setpSpinBox.setMaximum(1000.0)
        self.setpSpinBox.setProperty("value", 300.0)
        self.setpSpinBox.setObjectName("setpSpinBox")
        self.horizontalLayout_6.addWidget(self.setpSpinBox)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.sendButton = QtWidgets.QPushButton(self.groupBox)
        self.sendButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/send"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sendButton.setIcon(icon1)
        self.sendButton.setIconSize(QtCore.QSize(44, 16))
        self.sendButton.setObjectName("sendButton")
        self.horizontalLayout_8.addWidget(self.sendButton)
        self.updateButton = QtWidgets.QPushButton(self.groupBox)
        self.updateButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/update"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.updateButton.setIcon(icon2)
        self.updateButton.setObjectName("updateButton")
        self.horizontalLayout_8.addWidget(self.updateButton)
        self.seqButton = QtWidgets.QPushButton(self.groupBox)
        self.seqButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/macro"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.seqButton.setIcon(icon3)
        self.seqButton.setObjectName("seqButton")
        self.horizontalLayout_8.addWidget(self.seqButton)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.aLabel = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(16)
        self.aLabel.setFont(font)
        self.aLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.aLabel.setObjectName("aLabel")
        self.verticalLayout.addWidget(self.aLabel)
        self.bLabel = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(16)
        self.bLabel.setFont(font)
        self.bLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.bLabel.setObjectName("bLabel")
        self.verticalLayout.addWidget(self.bLabel)
        spacerItem1 = QtWidgets.QSpacerItem(20, 41, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.startButton = QtWidgets.QPushButton(self.groupBox)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/run"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.startButton.setIcon(icon4)
        self.startButton.setObjectName("startButton")
        self.horizontalLayout_9.addWidget(self.startButton)
        self.stopButton = QtWidgets.QPushButton(self.groupBox)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/stop"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stopButton.setIcon(icon5)
        self.stopButton.setObjectName("stopButton")
        self.horizontalLayout_9.addWidget(self.stopButton)
        self.clearButton = QtWidgets.QPushButton(self.groupBox)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/clear"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clearButton.setIcon(icon6)
        self.clearButton.setObjectName("clearButton")
        self.horizontalLayout_9.addWidget(self.clearButton)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10.addWidget(self.groupBox)

        self.retranslateUi(WLakeshore)
        QtCore.QMetaObject.connectSlotsByName(WLakeshore)

    def retranslateUi(self, WLakeshore):
        _translate = QtCore.QCoreApplication.translate
        WLakeshore.setWindowTitle(_translate("WLakeshore", "Lakeshore"))
        self.groupBox.setTitle(_translate("WLakeshore", "Setup"))
        self.label.setText(_translate("WLakeshore", "IP:"))
        self.label_8.setText(_translate("WLakeshore", "Output:"))
        self.outputComboBox.setItemText(0, _translate("WLakeshore", "1"))
        self.outputComboBox.setItemText(1, _translate("WLakeshore", "2"))
        self.label_9.setText(_translate("WLakeshore", "Sensor:"))
        self.sensorComboBox.setItemText(0, _translate("WLakeshore", "A"))
        self.sensorComboBox.setItemText(1, _translate("WLakeshore", "B"))
        self.sensorComboBox.setItemText(2, _translate("WLakeshore", "C"))
        self.sensorComboBox.setItemText(3, _translate("WLakeshore", "D"))
        self.label_2.setText(_translate("WLakeshore", "P:"))
        self.label_3.setText(_translate("WLakeshore", "I:"))
        self.label_4.setText(_translate("WLakeshore", "D:"))
        self.label_5.setText(_translate("WLakeshore", "Manual"))
        self.moutSpinBox.setSuffix(_translate("WLakeshore", " %"))
        self.label_6.setText(_translate("WLakeshore", "Range"))
        self.rangeComboBox.setItemText(0, _translate("WLakeshore", "Off"))
        self.rangeComboBox.setItemText(1, _translate("WLakeshore", "Low"))
        self.rangeComboBox.setItemText(2, _translate("WLakeshore", "Medium"))
        self.rangeComboBox.setItemText(3, _translate("WLakeshore", "High"))
        self.label_7.setText(_translate("WLakeshore", "Setpoint"))
        self.setpSpinBox.setSuffix(_translate("WLakeshore", " K"))
        self.aLabel.setText(_translate("WLakeshore", "A: 0 K"))
        self.bLabel.setText(_translate("WLakeshore", "B: 0 K"))
        self.startButton.setText(_translate("WLakeshore", "Start"))
        self.stopButton.setText(_translate("WLakeshore", "Stop"))
        self.clearButton.setText(_translate("WLakeshore", "Clear"))

from pyqtgraph import PlotWidget
from . import resources_rc

