Metrics/LineLength:
  Max: 120

Style/AndOr:
  EnforcedStyle: conditionals

Style/CaseIndentation:
  IndentOneStep: true

Style/PreferredHashMethods:
  Enabled: false

Style/BlockDelimiters:
  EnforcedStyle: line_count_based

Style/EmptyLinesAroundBlockBody:
  EnforcedStyle: no_empty_lines

Style/IfUnlessModifier:
  MaxLineLength: 120

Style/IndentationWidth:
  Width: 2

Style/MethodCallParentheses:
  Enabled: false

Style/MultilineIfThen:
  Enabled: true

Style/NegatedIf:
  Enabled: true

Style/Not:
  Enabled: false

Style/AndOr:
  Enabled: false

Style/SpaceInsideBrackets:
  Enabled: true

Style/StringLiterals:
  SupportedStyles:
    - single_quotes
    - double_quotes

Style/StringLiteralsInInterpolation:
  SupportedStyles:
    - single_quotes
    - double_quotes

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: no_comma

Style/UnneededInterpolation:
  Enabled: true
