language: python
sudo: false
python:
- '3.5'
install:
- pip install -e .
- pip install -r test_requirements.txt
- pip install pylint
script:
- py.test tests
- pylint --rcfile=.pylintrc cob
deploy:
  provider: pypi
  user: vmalloc
  password:
    secure: lPRJIhiuniYyIyV2jHHvK3IiQIckld92yYY2rfIutqa3wsdlSTXPGO1snBH0fxvhvfwudWrj1h4l3Ru8SN+s7AQwzMSFVSouU9HLtlxqzyYuL98iCDZa1YI2NNOU+OBByZNgbgldeuWPcIM+loIpte5yaMuW+90lbrYYjO7DFZaXjPhumE+rHfc+hXnRg8j0dnlpXtsVewDHF+6GMNtvG+rxG36ka9WF7JQvM28+1VltbmKQemuwgtBLAasNSaViQo3O3EI/vbWFmB9Rnv9rTV2DTfpWUvqQDtxcOokFi+DVFaEKaUb0gUA8RDUgYm7vdFeg8SiUW/uvjEzRHogPvGgbIHqpmgqKVtpxXTVVSNrp8gU6ElIm/fR/b5716YdWTlBBX840LjazCUcR4RUPHkw8VDIItTmcgYscQcSdX1xfmrc09EY/QcUBuhFNizCJZVvUsjBMr2zeAElQgWeWC5gtEDx4JGVRggcu9wotAArG4krDMo3SOqspE7i+SPkE7QZH8D4M6X8v0qUW4y1Vps5TnoLxe3ffuKD24huyI6KjmFdPfaDVXTGi3YL/98aPnK9y5juf5qjU05SHn7ldTPDxxHqkrziuztHun6OOx3PQna41lYisUww3gg+6Ch3SucUZVWd81278ulFGqrPYgJPlSawBHXa2bxD1dRr6edM=
  on:
    tags: true
    repo: getweber/cob
    branch: develop
