# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-26 19:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ovp_testimonials', '0005_auto_20170426_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='deleted_date',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='published_date',
        ),
    ]
