
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-04-26T16:19:10+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "5fb59f0eeda7961b61fc645ddefbcd2512854a33",
 "version": "v1.3.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
