
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-04-19T14:07:14-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "1a4a229bbe454ccb7f407ca216e7e1d8dda94b3c",
 "version": "0.9.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
