
# This file was generated by 'versioneer.py' (0.14) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '1.0.0'
version_full = '906cf6e46f75698bf0f87ce12661d48915a70ee0'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

