
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "5933615f9a967d80af0a7fba95f90ba5d471d1c3",
 "version": "0.2.12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
