
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "13c3ca756e0e899aa3f6969658dcc8fbdc719b73",
 "version": "1.1.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
