
#ifndef CASADI_NLPSOL_BONMIN_EXPORT_H
#define CASADI_NLPSOL_BONMIN_EXPORT_H

#ifdef CASADI_NLPSOL_BONMIN_STATIC_DEFINE
#  define CASADI_NLPSOL_BONMIN_EXPORT
#  define CASADI_NLPSOL_BONMIN_NO_EXPORT
#else
#  ifndef CASADI_NLPSOL_BONMIN_EXPORT
#    ifdef casadi_nlpsol_bonmin_EXPORTS
        /* We are building this library */
#      define CASADI_NLPSOL_BONMIN_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define CASADI_NLPSOL_BONMIN_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef CASADI_NLPSOL_BONMIN_NO_EXPORT
#    define CASADI_NLPSOL_BONMIN_NO_EXPORT 
#  endif
#endif

#ifndef CASADI_NLPSOL_BONMIN_DEPRECATED
#  define CASADI_NLPSOL_BONMIN_DEPRECATED 
#endif

#ifndef CASADI_NLPSOL_BONMIN_DEPRECATED_EXPORT
#  define CASADI_NLPSOL_BONMIN_DEPRECATED_EXPORT CASADI_NLPSOL_BONMIN_EXPORT CASADI_NLPSOL_BONMIN_DEPRECATED
#endif

#ifndef CASADI_NLPSOL_BONMIN_DEPRECATED_NO_EXPORT
#  define CASADI_NLPSOL_BONMIN_DEPRECATED_NO_EXPORT CASADI_NLPSOL_BONMIN_NO_EXPORT CASADI_NLPSOL_BONMIN_DEPRECATED
#endif

#define DEFINE_NO_DEPRECATED 0
#if DEFINE_NO_DEPRECATED
# define CASADI_NLPSOL_BONMIN_NO_DEPRECATED
#endif

#endif
