---
- name: Checkout pid1
  git:
    repo: https://github.com/Morgan-Stanley/treadmill-pid1.git
    dest: "{{base_dir}}/treadmill-pid1"

- name: Build pid1
  shell: make
  args:
    chdir: "{{base_dir}}/treadmill-pid1"

- name: Patch Treadmill deps
  file:
    path: "{{app_root}}/etc"
    state: directory

- name: Copy resolv.conf
  copy: remote_src=True src=/etc/resolv.conf dest="{{app_root}}/etc"

- name: Make the mount private
  command: "mount --make-rprivate /"

- name: Make local disk volume
  shell: "dd if=/dev/zero of={{app_root}}/treadmill.img seek=$((1024*1024*20)) count=1"

