# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 01:50
from __future__ import unicode_literals

import constellation_devicemanager.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('MAC', models.CharField(max_length=17, primary_key=True, serialize=False, validators=[constellation_devicemanager.validators.validate_mac])),
                ('name', models.CharField(max_length=64)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
