# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-27 05:43
from __future__ import unicode_literals

import constellation_devicemanager.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constellation_devicemanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='hostname',
            field=models.CharField(default='default', max_length=64, validators=[constellation_devicemanager.validators.validate_hostname]),
            preserve_default=False,
        ),
    ]
