- name: wait for SSH
  hosts: all
  gather_facts: false
  roles:
    - check_ssh

- name: upload files before
  hosts: all
  roles:
    - role: upload_files
      vars:
        upload_files: "{{ pre_upload_files }}"

- name: configure certificate authority, if necessary
  become: true
  hosts: certificate_authority
  gather_facts: false
  roles:
    - certificate_authority

- name: configure repositories
  become: true
  hosts: repositories
  roles:
    - repositories

- name: pre-configure jenkins
  become: true
  hosts: jenkins_master:jenkins_slave
  roles:
    - jenkins_common

- name: configure jenkins masters
  become: true
  hosts: jenkins_master
  roles:
    - beaker-client
    - jenkins_master
    - ntp

- name: configure jenkins slaves
  become: true
  hosts: jenkins_slave
  roles:
    - jenkins_slave
    - role: jenkins_slave_container_wrapup
      when: "'{{ ansible_connection }}' == 'docker'"

- name: configure container-based slaves
  hosts: jenkins_docker_slave
  roles:
    - jenkins_docker_slave

- name: upload files after
  hosts: all
  roles:
    - role: upload_files
      vars:
        upload_files: "{{ post_upload_files }}"
