resource_registry:
  OS::TripleO::Services::Collectd: ../puppet/services/metrics/collectd.yaml

# parameter_defaults:
#
## You can specify additional plugins to load using the
## CollectdExtraPlugins key:
#
#   CollectdExtraPlugins:
#     - disk
#     - df
#
## You can use ExtraConfig (or one of the related *ExtraConfig keys)
## to configure collectd.  See the documentation for puppet-collectd at
## https://github.com/voxpupuli/puppet-collectd for details.
#
#   ExtraConfig:
#     collectd::plugin::disk::disks:
#       - "/^[vhs]d[a-f][0-9]?$/"
#     collectd::plugin::df::mountpoints:
#       - "/"
#     collectd::plugin::df::ignoreselected: false
#     collectd::plugin::cpu::valuespercentage: true
