# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 14:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assetadapter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=200)),
                ('binding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assetadapter.Command')),
            ],
        ),
        migrations.CreateModel(
            name='DataEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2017, 4, 23, 14, 26, 56, 23014))),
                ('data', models.BinaryField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assetadapter.Asset')),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assetadapter.Entity')),
                ('name', models.CharField(max_length=200)),
            ],
            bases=('assetadapter.entity',),
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200)),
                ('binding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assetadapter.Property')),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='processengine.Process')),
            ],
        ),
        migrations.AddField(
            model_name='dataentry',
            name='process',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='processengine.Process'),
        ),
        migrations.AddField(
            model_name='action',
            name='scope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hooked_actions', to='processengine.Process'),
        ),
    ]
