# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('processengine', '0003_dataentry_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='process',
            name='status',
            field=models.CharField(choices=[('pending', 'F\xfcgg\u0151ben'), ('initialized', 'Inicializ\xe1lva'), ('running', 'Fut'), ('disabled', 'Inakt\xedv'), ('done', 'V\xe9gzett'), ('failure', 'Hiba')], default='pending', max_length=200),
        ),
        migrations.AddField(
            model_name='execution',
            name='executor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='processengine.Process'),
        ),
    ]
