# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 21:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('processengine', '0004_auto_20170430_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='execution',
            old_name='timestamp',
            new_name='begins',
        ),
        migrations.AddField(
            model_name='execution',
            name='ended',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='execution',
            name='status',
            field=models.CharField(choices=[('pending', 'F\xfcgg\u0151ben'), ('initialized', 'Inicializ\xe1lva'), ('running', 'Fut'), ('disabled', 'Inakt\xedv'), ('done', 'V\xe9gzett'), ('failure', 'Hiba')], default='pending', max_length=200),
        ),
    ]
