# Starts up a WAMP router suitable for running the examples in this directory
version: "2"
services:
  crossbar:
    image: crossbario/crossbar:community-pypy3-17.3.1
    volumes:
      - ./crossbar-config.yaml:/node/.crossbar/config.yaml:ro
    ports:
      - 127.0.0.1:8080:8080
    command: --config /node/.crossbar/config.yaml
