# coding: utf-8

"""
    Schul-Cloud Content API

    This is the specification for the content of Schul-Cloud. You can find more information in the repository <https://github.com/schul-cloud/ressources-api-v1>. 

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into sdk package
from .models.content_category import ContentCategory
from .models.dimensions import Dimensions
from .models.inline_response_200 import InlineResponse200
from .models.language import Language
from .models.license import License
from .models.provider import Provider
from .models.ressource import Ressource
from .models.subject import Subject
from .models.url import URL

# import apis into sdk package
from .apis.ressource_api import RessourceApi

# import ApiClient
from .api_client import ApiClient

from .configuration import Configuration

configuration = Configuration()
