# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omCmsMain', '0005_auto_20170322_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitemaininfo',
            name='active',
            field=models.BooleanField(default=False, unique=True),
        ),
    ]
