# You should not use special characture in the value keys
prefix:
  time_format: "%b %d %H:%M:%S"
  values:
    date: (\w+ \d\d)
    time: (\d\d:\d\d:\d\d)
    host: ([^ ]+)
    processName: (\w+)
    processId: (\d+)
    error: (\w+)
  line: '{date} {time}  {host} {processName}[{processId}]: {error}: '

messages:
  BGP_PREFIX_THRESH_EXCEEDED:
    values:
      peer: (\d+\.\d+\.\d+\.\d+)
      asn: (\d+)
      limit: (\d+)
      current: (\d+)
      table: (\w+)
      type: (\w+)
    line: '{peer} (External AS {asn}): Configured maximum prefix-limit threshold({limit}) exceeded for {table}-{type} nlri: {current} (instance master)'
    model: openconfig_bgp
    mapping:
      asn: bgp/neighbors/neighbor/{peer}/state/peer_as
      current: bgp/neighbors/neighbor/{peer}/afi_safis/afi_safi/{table}/state/prefixes/received
      limit: bgp/neighbors/neighbor/{peer}/afi_safis/afi_safi/{table}/ipv4_{type}/prefix_limit/state/max_prefixes
