
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "b41450e24c9f05955ecaa1a358ee8a15e32d8e25",
 "version": "3.0.0a25"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
