clouds:
  grizzly:
    credential:
      auth_url: https://keystone.example.com/v2.0/
      username: admin
      password: admin
      region_name: grizzly
    scope:
      project_id: 00000000000000000000000000000000
    ssh:
      username: foobar
      sudo_password: foobar
      connection_attempts: 3

  liberty:
    credential:
      auth_url: https://keystone.example.com/v2.0/
      username: admin
      password: admin
      region_name: liberty
    scope:
      project_id: 00000000000000000000000000000000
    ssh:
      username: foobar
      sudo_password: foobar
      connection_attempts: 3

# All objects are discovered by default, but list of discovered objects can
# be specified using discover parameter to cloud
#    discover:
#      - cloudferry.lib.os.discovery.keystone.Tenant
#      - cloudferry.lib.os.discovery.glance.Image
#      - cloudferry.lib.os.discovery.cinder.Volume
#      - cloudferry.lib.os.discovery.nova.Server

# Import legacy configuration
#  grizzly_src:
#    legacy: configuration.grizzly-juno.ini:src
#  juno_dst:
#    legacy: configuration.ini:dst

migrations:
  grizzly_to_liberty:
    source: grizzly
    destination: liberty
    objects:
      vms:
        - tenant.name: demo  # Include VMs owned by tenant named "demo" into migration
      images:
        - tenant.name: demo  # Include images owned by tenant named "demo" into migration
        - is_public: True    # Also include any public images (no matter owned by which tenant) into migration
      volumes:
        - tenant.name: demo  # Include volumes owned by tenant named "demo" into migration
