# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-02 23:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SidebarLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=75)),
                ('name', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=75)),
                ('description', models.CharField(max_length=512, null=True)),
                ('background', models.ImageField(blank=True, null=True, upload_to='background')),
            ],
        ),
        migrations.CreateModel(
            name='TitlebarLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=75)),
                ('name', models.CharField(max_length=75)),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constellation_base.SiteSetting')),
            ],
        ),
        migrations.AddField(
            model_name='sidebarlink',
            name='settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constellation_base.SiteSetting'),
        ),
    ]
