# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 09:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constellation_base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sidebarlink',
            name='settings',
        ),
        migrations.DeleteModel(
            name='SidebarLink',
        ),
    ]
