
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-04-01T17:23:52-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "2520f05ba00af8cf079de0f60f2ce23d68d0f6b5",
 "version": "0.5.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
