# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-11 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('function', models.TextField()),
                ('exception', models.TextField(blank=True, default=b'', null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('installation_id', models.CharField(help_text=b'System installation id (different for each corenetwork installation)', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='tags',
            field=models.ManyToManyField(to='corenetwork.Tag'),
        ),
    ]