# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constellation_orderboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='units',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='card',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
