language: python
matrix:
  include:
    - os: linux
      python: 2.7
      env: CC=gcc-5 CXX=g++-5
    - os: linux
      python: 3.3
      env: CC=gcc-5 CXX=g++-5
    - os: linux
      python: 3.4
      env: CC=gcc-5 CXX=g++-5
    - os: linux
      python: 3.5
      env: CC=gcc-5 CXX=g++-5
    - os: osx
      language: generic
      env: PYENV_VERSION=2.7.11
    - os: osx
      language: generic
      env: PYENV_VERSION=3.5.1
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - jags
    - gcc-5
    - g++-5
install:
  - ./.travis/install.sh
script:
  - ./.travis/script.sh
