# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omCmsMain', '0012_auto_20170322_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitemaininfo',
            name='siteHomeLabel',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
