# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omCmsMain', '0030_auto_20170410_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitemaininfo',
            name='displayDrawrMenu',
            field=models.BooleanField(default=True),
        ),
    ]
