# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omCmsMain', '0039_auto_20170416_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitemaininfo',
            name='showSiteHomeLabel',
            field=models.BooleanField(default=True),
        ),
    ]
