# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('omCmsMain', '0010_sitemaininfo_displayslideshow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryitem',
            name='itemLayout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='omCmsMain.itemLayout', to_field='itemLayoutName'),
        ),
    ]
