# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omCmsMain', '0016_categoryitem_itemsbyline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentarticle',
            name='articleFooter',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='contentarticle',
            name='body1',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='contentarticle',
            name='body1Image',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='contentarticle',
            name='body2',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='contentarticle',
            name='body2Image',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='contentarticle',
            name='subTitle',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='contentarticle',
            name='teaser',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='contentarticle',
            name='teaserImage',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
