# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omCmsMain', '0037_categoryitem_itemreadmore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentarticle',
            name='teaser',
            field=models.TextField(blank=True, null=True),
        ),
    ]
