
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "c82c4b9c280ee7538cad4b90989be94cd88ab294",
 "version": "0.post.dev417"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
