# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 18:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visaweb', '0002_auto_20170417_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='getter_command',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='getter_command', to='visaweb.Command'),
        ),
        migrations.AlterField(
            model_name='property',
            name='setter_command',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setter_command', to='visaweb.Command'),
        ),
    ]
