##############################################################################
# Copyright (c) 2017 ZTE Corporation and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

- hosts: hosts
  become: yes
  remote_user: root

  tasks:
    - name: Make some directories needed
      file:
        path: '{{ ansible_env.HOME }}/qtip_result/{{ ansible_hostname }}/dpi/'
        state: directory

    - include: ../inxi.yaml
      vars:
        dest_path: '{{ ansible_env.HOME }}/qtip_result/{{ ansible_hostname }}/dpi/'

    - include: ../top.yaml
      vars:
        dest_path: '{{ ansible_env.HOME }}/qtip_result/{{ ansible_hostname }}/dpi/'

    - name: Run nDPI benchmark
      shell: ./dpi_average.sh
      args:
        chdir: '{{ ansible_env.HOME }}/tempD/nDPI/example/'

    - name: Copying result and system info to qtip result directory
      command: cp $HOME/tempD/nDPI/example/dpi_dump.txt ./
      args:
        chdir: '{{ ansible_env.HOME }}/qtip_result/{{ ansible_hostname }}/dpi/'

    - name: Fetch result files to local manchine
      synchronize:
        mode: pull
        src: '{{ ansible_env.HOME }}/qtip_result/'
        dest: '{{ result_dir }}/'
