# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BladePy0_1_1\preferences_modules\preferencesUI.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_PreferencesDialog(object):
    def setupUi(self, PreferencesDialog):
        PreferencesDialog.setObjectName(_fromUtf8("PreferencesDialog"))
        PreferencesDialog.setWindowModality(QtCore.Qt.NonModal)
        PreferencesDialog.resize(470, 530)
        PreferencesDialog.setMaximumSize(QtCore.QSize(470, 530))
        PreferencesDialog.setWhatsThis(_fromUtf8(""))
        PreferencesDialog.setAutoFillBackground(False)
        PreferencesDialog.setInputMethodHints(QtCore.Qt.ImhNone)
        self.PreferencesDialog_vl = QtGui.QVBoxLayout(PreferencesDialog)
        self.PreferencesDialog_vl.setObjectName(_fromUtf8("PreferencesDialog_vl"))
        self.ui_preferences_tab = QtGui.QTabWidget(PreferencesDialog)
        self.ui_preferences_tab.setObjectName(_fromUtf8("ui_preferences_tab"))
        self.ui_preferences_general_tab = QtGui.QWidget()
        self.ui_preferences_general_tab.setObjectName(_fromUtf8("ui_preferences_general_tab"))
        self.ui_preferences_general_tab_vl = QtGui.QVBoxLayout(self.ui_preferences_general_tab)
        self.ui_preferences_general_tab_vl.setObjectName(_fromUtf8("ui_preferences_general_tab_vl"))
        self.ui_preferences_general_groupbox = QtGui.QGroupBox(self.ui_preferences_general_tab)
        self.ui_preferences_general_groupbox.setObjectName(_fromUtf8("ui_preferences_general_groupbox"))
        self.ui_preferences_general_groupbox_gl = QtGui.QGridLayout(self.ui_preferences_general_groupbox)
        self.ui_preferences_general_groupbox_gl.setObjectName(_fromUtf8("ui_preferences_general_groupbox_gl"))
        self.self_preferences_general_outputs_groupbox = QtGui.QGroupBox(self.ui_preferences_general_groupbox)
        self.self_preferences_general_outputs_groupbox.setObjectName(_fromUtf8("self_preferences_general_outputs_groupbox"))
        self.self_preferences_general_outputs_groupbox_vl = QtGui.QVBoxLayout(self.self_preferences_general_outputs_groupbox)
        self.self_preferences_general_outputs_groupbox_vl.setObjectName(_fromUtf8("self_preferences_general_outputs_groupbox_vl"))
        self.ui_preferences_general_outputs_description_lbl = QtGui.QLabel(self.self_preferences_general_outputs_groupbox)
        self.ui_preferences_general_outputs_description_lbl.setTextFormat(QtCore.Qt.AutoText)
        self.ui_preferences_general_outputs_description_lbl.setObjectName(_fromUtf8("ui_preferences_general_outputs_description_lbl"))
        self.self_preferences_general_outputs_groupbox_vl.addWidget(self.ui_preferences_general_outputs_description_lbl)
        self.self_preferences_general_outputs_gl = QtGui.QGridLayout()
        self.self_preferences_general_outputs_gl.setObjectName(_fromUtf8("self_preferences_general_outputs_gl"))
        self.ui_preferences_tecplot_2d_chk = QtGui.QCheckBox(self.self_preferences_general_outputs_groupbox)
        self.ui_preferences_tecplot_2d_chk.setChecked(True)
        self.ui_preferences_tecplot_2d_chk.setObjectName(_fromUtf8("ui_preferences_tecplot_2d_chk"))
        self.self_preferences_general_outputs_gl.addWidget(self.ui_preferences_tecplot_2d_chk, 3, 0, 1, 1)
        self.ui_preferences_igs_3d_cur_exception_edit = QtGui.QLineEdit(self.self_preferences_general_outputs_groupbox)
        self.ui_preferences_igs_3d_cur_exception_edit.setInputMask(_fromUtf8(""))
        self.ui_preferences_igs_3d_cur_exception_edit.setObjectName(_fromUtf8("ui_preferences_igs_3d_cur_exception_edit"))
        self.self_preferences_general_outputs_gl.addWidget(self.ui_preferences_igs_3d_cur_exception_edit, 1, 1, 1, 1)
        self.ui_preferences_igs_2d_cur_chk = QtGui.QCheckBox(self.self_preferences_general_outputs_groupbox)
        self.ui_preferences_igs_2d_cur_chk.setObjectName(_fromUtf8("ui_preferences_igs_2d_cur_chk"))
        self.self_preferences_general_outputs_gl.addWidget(self.ui_preferences_igs_2d_cur_chk, 2, 0, 1, 1)
        self.ui_preferences_igs_3d_cur_chk = QtGui.QCheckBox(self.self_preferences_general_outputs_groupbox)
        self.ui_preferences_igs_3d_cur_chk.setChecked(True)
        self.ui_preferences_igs_3d_cur_chk.setObjectName(_fromUtf8("ui_preferences_igs_3d_cur_chk"))
        self.self_preferences_general_outputs_gl.addWidget(self.ui_preferences_igs_3d_cur_chk, 1, 0, 1, 1)
        self.ui_preferences_igs_surf_chk = QtGui.QCheckBox(self.self_preferences_general_outputs_groupbox)
        self.ui_preferences_igs_surf_chk.setChecked(True)
        self.ui_preferences_igs_surf_chk.setObjectName(_fromUtf8("ui_preferences_igs_surf_chk"))
        self.self_preferences_general_outputs_gl.addWidget(self.ui_preferences_igs_surf_chk, 0, 0, 1, 1)
        self.ui_preferences_igs_2d_cur_exception_edit = QtGui.QLineEdit(self.self_preferences_general_outputs_groupbox)
        self.ui_preferences_igs_2d_cur_exception_edit.setInputMask(_fromUtf8(""))
        self.ui_preferences_igs_2d_cur_exception_edit.setText(_fromUtf8(""))
        self.ui_preferences_igs_2d_cur_exception_edit.setObjectName(_fromUtf8("ui_preferences_igs_2d_cur_exception_edit"))
        self.self_preferences_general_outputs_gl.addWidget(self.ui_preferences_igs_2d_cur_exception_edit, 2, 1, 1, 1)
        self.ui_preferences_igs_surf_exception_edit = QtGui.QLineEdit(self.self_preferences_general_outputs_groupbox)
        self.ui_preferences_igs_surf_exception_edit.setInputMask(_fromUtf8(""))
        self.ui_preferences_igs_surf_exception_edit.setObjectName(_fromUtf8("ui_preferences_igs_surf_exception_edit"))
        self.self_preferences_general_outputs_gl.addWidget(self.ui_preferences_igs_surf_exception_edit, 0, 1, 1, 1)
        self.self_preferences_general_outputs_groupbox_vl.addLayout(self.self_preferences_general_outputs_gl)
        self.ui_preferences_general_groupbox_gl.addWidget(self.self_preferences_general_outputs_groupbox, 1, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.ui_preferences_general_groupbox_gl.addItem(spacerItem, 3, 0, 1, 1)
        self.self_preferences_general_shape_groupbox = QtGui.QGroupBox(self.ui_preferences_general_groupbox)
        self.self_preferences_general_shape_groupbox.setObjectName(_fromUtf8("self_preferences_general_shape_groupbox"))
        self.self_preferences_general_shape_groupbox_vl = QtGui.QVBoxLayout(self.self_preferences_general_shape_groupbox)
        self.self_preferences_general_shape_groupbox_vl.setObjectName(_fromUtf8("self_preferences_general_shape_groupbox_vl"))
        self.ui_preferences_general_shape_gl = QtGui.QGridLayout()
        self.ui_preferences_general_shape_gl.setObjectName(_fromUtf8("ui_preferences_general_shape_gl"))
        self.ui_preferences_default_color_combo = QtGui.QComboBox(self.self_preferences_general_shape_groupbox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_preferences_default_color_combo.sizePolicy().hasHeightForWidth())
        self.ui_preferences_default_color_combo.setSizePolicy(sizePolicy)
        self.ui_preferences_default_color_combo.setMaximumSize(QtCore.QSize(16777215, 23))
        self.ui_preferences_default_color_combo.setObjectName(_fromUtf8("ui_preferences_default_color_combo"))
        self.ui_preferences_default_color_combo.addItem(_fromUtf8(""))
        self.ui_preferences_default_color_combo.addItem(_fromUtf8(""))
        self.ui_preferences_default_color_combo.addItem(_fromUtf8(""))
        self.ui_preferences_default_color_combo.addItem(_fromUtf8(""))
        self.ui_preferences_default_color_combo.addItem(_fromUtf8(""))
        self.ui_preferences_default_color_combo.addItem(_fromUtf8(""))
        self.ui_preferences_general_shape_gl.addWidget(self.ui_preferences_default_color_combo, 0, 1, 1, 1)
        self.ui_preferences_default_quality_dspn = QtGui.QDoubleSpinBox(self.self_preferences_general_shape_groupbox)
        self.ui_preferences_default_quality_dspn.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_preferences_default_quality_dspn.sizePolicy().hasHeightForWidth())
        self.ui_preferences_default_quality_dspn.setSizePolicy(sizePolicy)
        self.ui_preferences_default_quality_dspn.setMaximumSize(QtCore.QSize(16777215, 23))
        self.ui_preferences_default_quality_dspn.setAutoFillBackground(False)
        self.ui_preferences_default_quality_dspn.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.ui_preferences_default_quality_dspn.setMinimum(0.01)
        self.ui_preferences_default_quality_dspn.setSingleStep(0.2)
        self.ui_preferences_default_quality_dspn.setProperty("value", 1.0)
        self.ui_preferences_default_quality_dspn.setObjectName(_fromUtf8("ui_preferences_default_quality_dspn"))
        self.ui_preferences_general_shape_gl.addWidget(self.ui_preferences_default_quality_dspn, 2, 1, 1, 1)
        self.ui_preferences_default_transparency_dspn = QtGui.QDoubleSpinBox(self.self_preferences_general_shape_groupbox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_preferences_default_transparency_dspn.sizePolicy().hasHeightForWidth())
        self.ui_preferences_default_transparency_dspn.setSizePolicy(sizePolicy)
        self.ui_preferences_default_transparency_dspn.setMaximumSize(QtCore.QSize(16777215, 23))
        self.ui_preferences_default_transparency_dspn.setMaximum(1.0)
        self.ui_preferences_default_transparency_dspn.setSingleStep(0.1)
        self.ui_preferences_default_transparency_dspn.setObjectName(_fromUtf8("ui_preferences_default_transparency_dspn"))
        self.ui_preferences_general_shape_gl.addWidget(self.ui_preferences_default_transparency_dspn, 1, 1, 1, 1)
        self.ui_preferences_transparency_lbl_2 = QtGui.QLabel(self.self_preferences_general_shape_groupbox)
        self.ui_preferences_transparency_lbl_2.setObjectName(_fromUtf8("ui_preferences_transparency_lbl_2"))
        self.ui_preferences_general_shape_gl.addWidget(self.ui_preferences_transparency_lbl_2, 2, 0, 1, 1)
        self.ui_preferences_default_color_lbl = QtGui.QLabel(self.self_preferences_general_shape_groupbox)
        self.ui_preferences_default_color_lbl.setObjectName(_fromUtf8("ui_preferences_default_color_lbl"))
        self.ui_preferences_general_shape_gl.addWidget(self.ui_preferences_default_color_lbl, 0, 0, 1, 1)
        self.ui_preferences_transparency_lbl = QtGui.QLabel(self.self_preferences_general_shape_groupbox)
        self.ui_preferences_transparency_lbl.setObjectName(_fromUtf8("ui_preferences_transparency_lbl"))
        self.ui_preferences_general_shape_gl.addWidget(self.ui_preferences_transparency_lbl, 1, 0, 1, 1)
        self.self_preferences_general_shape_groupbox_vl.addLayout(self.ui_preferences_general_shape_gl)
        self.ui_preferences_general_groupbox_gl.addWidget(self.self_preferences_general_shape_groupbox, 2, 0, 1, 1)
        self.self_preferences_general_display_groupbox = QtGui.QGroupBox(self.ui_preferences_general_groupbox)
        self.self_preferences_general_display_groupbox.setObjectName(_fromUtf8("self_preferences_general_display_groupbox"))
        self.ui_preferences_general_groupbox_vl = QtGui.QVBoxLayout(self.self_preferences_general_display_groupbox)
        self.ui_preferences_general_groupbox_vl.setObjectName(_fromUtf8("ui_preferences_general_groupbox_vl"))
        self.self_preferences_general_display_gl = QtGui.QGridLayout()
        self.self_preferences_general_display_gl.setObjectName(_fromUtf8("self_preferences_general_display_gl"))
        self.ui_preferences_zoom_dpsn = QtGui.QDoubleSpinBox(self.self_preferences_general_display_groupbox)
        self.ui_preferences_zoom_dpsn.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_preferences_zoom_dpsn.sizePolicy().hasHeightForWidth())
        self.ui_preferences_zoom_dpsn.setSizePolicy(sizePolicy)
        self.ui_preferences_zoom_dpsn.setAutoFillBackground(False)
        self.ui_preferences_zoom_dpsn.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.ui_preferences_zoom_dpsn.setMinimum(1.01)
        self.ui_preferences_zoom_dpsn.setSingleStep(0.1)
        self.ui_preferences_zoom_dpsn.setProperty("value", 1.01)
        self.ui_preferences_zoom_dpsn.setObjectName(_fromUtf8("ui_preferences_zoom_dpsn"))
        self.self_preferences_general_display_gl.addWidget(self.ui_preferences_zoom_dpsn, 1, 1, 1, 1)
        self.ui_preferences_zoom_lbl = QtGui.QLabel(self.self_preferences_general_display_groupbox)
        self.ui_preferences_zoom_lbl.setObjectName(_fromUtf8("ui_preferences_zoom_lbl"))
        self.self_preferences_general_display_gl.addWidget(self.ui_preferences_zoom_lbl, 1, 0, 1, 1)
        self.ui_preferences_general_groupbox_vl.addLayout(self.self_preferences_general_display_gl)
        self.ui_preferences_general_groupbox_gl.addWidget(self.self_preferences_general_display_groupbox, 0, 0, 1, 1)
        self.ui_preferences_general_tab_vl.addWidget(self.ui_preferences_general_groupbox)
        self.ui_preferences_tab.addTab(self.ui_preferences_general_tab, _fromUtf8(""))
        self.ui_preferences_bladepro_tab = QtGui.QWidget()
        self.ui_preferences_bladepro_tab.setObjectName(_fromUtf8("ui_preferences_bladepro_tab"))
        self.verticalLayout = QtGui.QVBoxLayout(self.ui_preferences_bladepro_tab)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.ui_preferences_bladepro_groupbox = QtGui.QGroupBox(self.ui_preferences_bladepro_tab)
        self.ui_preferences_bladepro_groupbox.setObjectName(_fromUtf8("ui_preferences_bladepro_groupbox"))
        self.ui_preferences_bladepro_groupbox_vl = QtGui.QGridLayout(self.ui_preferences_bladepro_groupbox)
        self.ui_preferences_bladepro_groupbox_vl.setObjectName(_fromUtf8("ui_preferences_bladepro_groupbox_vl"))
        self.ui_preferences_bladepro_groupbox_vl_hl = QtGui.QHBoxLayout()
        self.ui_preferences_bladepro_groupbox_vl_hl.setObjectName(_fromUtf8("ui_preferences_bladepro_groupbox_vl_hl"))
        self.ui_preferences_running_bladepro_version_lbl = QtGui.QLabel(self.ui_preferences_bladepro_groupbox)
        self.ui_preferences_running_bladepro_version_lbl.setObjectName(_fromUtf8("ui_preferences_running_bladepro_version_lbl"))
        self.ui_preferences_bladepro_groupbox_vl_hl.addWidget(self.ui_preferences_running_bladepro_version_lbl)
        self.ui_preferences_running_bladepro_version_edit = QtGui.QLineEdit(self.ui_preferences_bladepro_groupbox)
        self.ui_preferences_running_bladepro_version_edit.setObjectName(_fromUtf8("ui_preferences_running_bladepro_version_edit"))
        self.ui_preferences_bladepro_groupbox_vl_hl.addWidget(self.ui_preferences_running_bladepro_version_edit)
        self.ui_preferences_bladepro_groupbox_vl.addLayout(self.ui_preferences_bladepro_groupbox_vl_hl, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.ui_preferences_bladepro_groupbox)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.ui_preferences_tab.addTab(self.ui_preferences_bladepro_tab, _fromUtf8(""))
        self.PreferencesDialog_vl.addWidget(self.ui_preferences_tab)
        self.ui_preferences_okcancelapply_hl = QtGui.QHBoxLayout()
        self.ui_preferences_okcancelapply_hl.setObjectName(_fromUtf8("ui_preferences_okcancelapply_hl"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.ui_preferences_okcancelapply_hl.addItem(spacerItem2)
        self.ui_preferences_ok_btn = QtGui.QPushButton(PreferencesDialog)
        self.ui_preferences_ok_btn.setObjectName(_fromUtf8("ui_preferences_ok_btn"))
        self.ui_preferences_okcancelapply_hl.addWidget(self.ui_preferences_ok_btn)
        self.ui_preferences_cancel_btn = QtGui.QPushButton(PreferencesDialog)
        self.ui_preferences_cancel_btn.setObjectName(_fromUtf8("ui_preferences_cancel_btn"))
        self.ui_preferences_okcancelapply_hl.addWidget(self.ui_preferences_cancel_btn)
        self.ui_preferences_apply_btn = QtGui.QPushButton(PreferencesDialog)
        self.ui_preferences_apply_btn.setObjectName(_fromUtf8("ui_preferences_apply_btn"))
        self.ui_preferences_okcancelapply_hl.addWidget(self.ui_preferences_apply_btn)
        self.PreferencesDialog_vl.addLayout(self.ui_preferences_okcancelapply_hl)

        self.retranslateUi(PreferencesDialog)
        self.ui_preferences_tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(PreferencesDialog)

    def retranslateUi(self, PreferencesDialog):
        PreferencesDialog.setWindowTitle(_translate("PreferencesDialog", "Preferences", None))
        self.ui_preferences_general_groupbox.setTitle(_translate("PreferencesDialog", "General", None))
        self.self_preferences_general_outputs_groupbox.setToolTip(_translate("PreferencesDialog", "The ouputs checked will be displayed when loading a case. One can make exceptions when displaying IGS files.", None))
        self.self_preferences_general_outputs_groupbox.setTitle(_translate("PreferencesDialog", "BladePro Outputs Loaded by Case", None))
        self.ui_preferences_general_outputs_description_lbl.setText(_translate("PreferencesDialog", "<html><head/><body><p><span style=\" font-weight:600;\">Fields are exceptions that will not be displayed by default</span></p></body></html>", None))
        self.ui_preferences_tecplot_2d_chk.setText(_translate("PreferencesDialog", "Tecplot 2D", None))
        self.ui_preferences_igs_3d_cur_exception_edit.setToolTip(_translate("PreferencesDialog", "The parts in this field will not be initially displayed in the Output Viewer when loading a IGS 3D Curves", None))
        self.ui_preferences_igs_3d_cur_exception_edit.setText(_translate("PreferencesDialog", "HUB; SHROUD", None))
        self.ui_preferences_igs_2d_cur_chk.setText(_translate("PreferencesDialog", "IGS 2D Curves", None))
        self.ui_preferences_igs_3d_cur_chk.setText(_translate("PreferencesDialog", "IGS 3D Curves", None))
        self.ui_preferences_igs_surf_chk.setText(_translate("PreferencesDialog", "IGS Surf", None))
        self.ui_preferences_igs_surf_exception_edit.setToolTip(_translate("PreferencesDialog", "The parts in this field will not be initially displayed in the Output Viewer when loading a IGS surf", None))
        self.ui_preferences_igs_surf_exception_edit.setText(_translate("PreferencesDialog", "HUB; SHROUD; STREAM", None))
        self.self_preferences_general_shape_groupbox.setStatusTip(_translate("PreferencesDialog", "Part Controls", None))
        self.self_preferences_general_shape_groupbox.setTitle(_translate("PreferencesDialog", "Part Controls", None))
        self.ui_preferences_default_color_combo.setItemText(0, _translate("PreferencesDialog", "Golden", None))
        self.ui_preferences_default_color_combo.setItemText(1, _translate("PreferencesDialog", "Blue", None))
        self.ui_preferences_default_color_combo.setItemText(2, _translate("PreferencesDialog", "Red", None))
        self.ui_preferences_default_color_combo.setItemText(3, _translate("PreferencesDialog", "White", None))
        self.ui_preferences_default_color_combo.setItemText(4, _translate("PreferencesDialog", "Black", None))
        self.ui_preferences_default_color_combo.setItemText(5, _translate("PreferencesDialog", "Yellow", None))
        self.ui_preferences_transparency_lbl_2.setText(_translate("PreferencesDialog", "Default Shape Quality", None))
        self.ui_preferences_default_color_lbl.setText(_translate("PreferencesDialog", "Default Shape Color", None))
        self.ui_preferences_transparency_lbl.setText(_translate("PreferencesDialog", "Default Shape Transparency", None))
        self.self_preferences_general_display_groupbox.setStatusTip(_translate("PreferencesDialog", "Display controls", None))
        self.self_preferences_general_display_groupbox.setTitle(_translate("PreferencesDialog", "Display", None))
        self.ui_preferences_zoom_dpsn.setToolTip(_translate("PreferencesDialog", "Percentage of zooming by mouse wheel scroll", None))
        self.ui_preferences_zoom_dpsn.setStatusTip(_translate("PreferencesDialog", "Amount of percentage of zooming by wheel scroll", None))
        self.ui_preferences_zoom_lbl.setStatusTip(_translate("PreferencesDialog", "Zoom Step: The amount of zoom when scrolling mouse\'s wheel", None))
        self.ui_preferences_zoom_lbl.setText(_translate("PreferencesDialog", "Zoom Step", None))
        self.ui_preferences_tab.setTabText(self.ui_preferences_tab.indexOf(self.ui_preferences_general_tab), _translate("PreferencesDialog", "General", None))
        self.ui_preferences_bladepro_groupbox.setTitle(_translate("PreferencesDialog", "BladePro", None))
        self.ui_preferences_running_bladepro_version_lbl.setText(_translate("PreferencesDialog", "Running Version", None))
        self.ui_preferences_running_bladepro_version_edit.setText(_translate("PreferencesDialog", "bladepro", None))
        self.ui_preferences_tab.setTabText(self.ui_preferences_tab.indexOf(self.ui_preferences_bladepro_tab), _translate("PreferencesDialog", "BladePro", None))
        self.ui_preferences_ok_btn.setText(_translate("PreferencesDialog", "OK", None))
        self.ui_preferences_cancel_btn.setText(_translate("PreferencesDialog", "Cancel", None))
        self.ui_preferences_apply_btn.setText(_translate("PreferencesDialog", "Apply", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    PreferencesDialog = QtGui.QWidget()
    ui = Ui_PreferencesDialog()
    ui.setupUi(PreferencesDialog)
    PreferencesDialog.show()
    sys.exit(app.exec_())

