# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visaweb', '0014_auto_20170311_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visadevice',
            name='alias',
            field=models.CharField(default='85a76579-0537-4b61-9235-124d8e875507', max_length=200),
        ),
    ]
