# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visaweb', '0015_auto_20170312_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visadevice',
            name='alias',
            field=models.CharField(default=b'da1467ab-4df7-4645-ae25-a7428e5db5e9', max_length=200),
        ),
    ]
