# coding: utf-8

"""
    Gmail

    Access Gmail mailboxes including sending user email.

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import gmail_client
from gmail_client.rest import ApiException
from gmail_client.models.list_forwarding_addresses_response import ListForwardingAddressesResponse


class TestListForwardingAddressesResponse(unittest.TestCase):
    """ ListForwardingAddressesResponse unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListForwardingAddressesResponse(self):
        """
        Test ListForwardingAddressesResponse
        """
        model = gmail_client.models.list_forwarding_addresses_response.ListForwardingAddressesResponse()


if __name__ == '__main__':
    unittest.main()
