
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "29e3d1eb93421e39713129a88b82666f2e49f8e1",
 "version": "0.0.0a38"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
