# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 22:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('omCmsMain', '0017_auto_20170322_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentarticle',
            name='articleCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='omCmsMain.categoryItem', to_field='itemCategory'),
        ),
    ]
